### ISSUE TITLE
Cloud image created as per latest kairos version/documentation fails to run recovery stage and come up after that

### ISSUE THREAD

**Issue by nano2007** [kairos-io/kairos#1664] opened 2023-07-31 09:15 UTC
**Kairos version:**

NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
KAIROS_NAME="kairos-core-opensuse-leap"
KAIROS_VERSION="v2.3.0-26-g81f3280"
KAIROS_ID="kairos"
KAIROS_ID_LIKE="kairos-core-opensuse-leap"
KAIROS_VERSION_ID="v2.3.0-26-g81f3280"
KAIROS_PRETTY_NAME="kairos-core-opensuse-leap v2.3.0-26-g81f3280"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/core-opensuse-leap"
KAIROS_IMAGE_LABEL="latest"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_VARIANT="core"
KAIROS_FLAVOR="opensuse-leap"

**CPU architecture, OS, and Version:**

Linux cos-recovery 5.14.21-150500.55.7-default #1 SMP PREEMPT_DYNAMIC Mon Jul 10 18:53:13 UTC 2023 (4204a3a) x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**

cloud image fails to install/come up with latest Kairos version.

**To Reproduce**

Apply the yaml file described at https://kairos.io/docs/advanced/build/#build-a-cloud-image. A cloud image gets generated. I try to start a VM with the generated image, but the system gets stuck at cos-recovery prompt.

Note: the yaml needs a modification as the v1alpha1 apiversion is no longer valid. This has to be changed to v1alpha2

**Expected behavior**

The system should reset and all services should come up normally.

**Logs**

Logs attached (system.log)

**Additional context**

None

**Comment by nano2007** [comment] 2023-07-31 09:16
[system.log](https://github.com/kairos-io/kairos/files/12213459/system.log)

**Comment by mauromorales** [comment] 2023-07-31 09:34
There was an issue with the documentation and got updated in https://github.com/kairos-io/kairos-docs/commit/fc74bca36eb67b67aede8c09b7f9d566fd7f58b8

Could you please try it out and let us know if the issue persists?

**Comment by mauromorales** [comment] 2023-07-31 09:43
I wonder why the agent version shows as `kairos-agent version v0.0.1`

@Itxaka you might have a better idea what is going on here

**Comment by Itxaka** [comment] 2023-07-31 09:47
> I wonder why the agent version shows as `kairos-agent version v0.0.1`
> 
> @Itxaka you might have a better idea what is going on here

Default value. Whatever is building the binary is not setting the proper version, so probably the packages building are setting the -X to a wrongly path?

**Comment by mauromorales** [comment] 2023-07-31 09:59
@Itxaka yeah good point ... ok but probably it is the right version running, so the version is not related to the error that @nano2007 is getting

**Comment by Itxaka** [comment] 2023-07-31 11:24
> @Itxaka yeah good point ... ok but probably it is the right version running, so the version is not related to the error that @nano2007 is getting

got it, its due to the module name change from kairos to kairos-agent to the package doesnt update the version. Fixing....

**Comment by Itxaka** [comment] 2023-07-31 11:27
https://github.com/kairos-io/packages/pull/353

**Comment by Itxaka** [comment] 2023-07-31 11:34
This may be due using a master version, which included a kairos-agent version which was an RC version as those were half broken in the reset and upgrade paths due to all the config loading changes.

When was the image built @nano2007 ?

**Comment by nano2007** [comment] 2023-07-31 11:41
I built the image this morning @Itxaka

**Comment by Itxaka** [comment] 2023-07-31 11:56
mmmh, ok, will try to reproduce locally with kind

**Comment by Itxaka** [comment] 2023-07-31 12:08
Image built with teh raw_images script results into:

```
DEBU[2023-07-31T12:03:05Z] Output of udevadm settle:                    
DEBU[2023-07-31T12:03:05Z] running command `blkid -l --match-token LABEL=COS_RECOVERY -o device` 
DEBU[2023-07-31T12:03:05Z] running command `lsblk -npo pkname /dev/vda4
` 
DEBU[2023-07-31T12:03:05Z] Got device /dev/vda for label COS_RECOVERY   
DEBU[2023-07-31T12:03:05Z] running command `sgdisk --verify /dev/vda`   
DEBU[2023-07-31T12:03:05Z] running command `sgdisk -p /dev/vda`         
WARN[2023-07-31T12:03:05Z] Not enough unpartitioned space in disk to operate
````


which is very weird. Partitions:

```
kairos@cos-recovery:~> sudo blkid
/dev/loop0: TYPE="squashfs"
/dev/vda4: LABEL="COS_RECOVERY" UUID="00904a35-1aea-4f37-976f-d66e74984a3d" BLOCK_SIZE="4096" TYPE="ext2" PARTLABEL="root" PARTUUID="86e5fc77-70fb-417d-95b1-796639c4cb42"
/dev/vda2: SEC_TYPE="msdos" LABEL_FATBOOT="COS_GRUB" LABEL="COS_GRUB" UUID="F707-8851" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="UEFI" PARTUUID="975fa281-b956-44dd-a444-d25e64edf09e"
/dev/vda5: LABEL="COS_STATE" UUID="cdf20c0d-9c58-4223-9b4b-62359cdea8d2" BLOCK_SIZE="4096" TYPE="ext2" PARTLABEL="state" PARTUUID="18965fdf-f122-4c5f-abb4-a3de0ae9418c"
/dev/vda3: LABEL="COS_OEM" UUID="29601de3-d90c-46be-a6c6-1e530182cd37" BLOCK_SIZE="1024" TYPE="ext2" PARTLABEL="oem" PARTUUID="e1916a30-eeac-4abf-b2e9-16eb7c41f8a5"
/dev/vda1: PARTLABEL="legacy" PARTUUID="08d31338-14df-410e-b4ee-e8090c08b66b"
/dev/vda6: LABEL="COS_PERSISTENT" UUID="db5d4554-7945-428b-af51-1c2050f67ca6" BLOCK_SIZE="4096" TYPE="ext2" PARTLABEL="persistent" PARTUUID="cda02d1f-7a4d-41a8-a3ab-f5d70b5b9686"
```

@nano2007 can you run `sudo blkid` in your generated image and post it? Im wondering if my dev image is broken due to not using the k8s osbuilder stuff

**Comment by nano2007** [comment] 2023-07-31 12:26
```
cepadmin@whkvmvenudeb11:/var/lib/rancher/k3s/storage/pvc-0890644f-14b1-49e6-8a74-e15675d5a5bd_default_hello-kairos4-artifacts$ sudo sgdisk --verify  hello-kairos4.raw

No problems found. 4029 free sectors (2.0 MiB) available in 2
segments, the largest of which is 2015 (1007.5 KiB) in size.
```
```
cepadmin@whkvmvenudeb11:/var/lib/rancher/k3s/storage/pvc-0890644f-14b1-49e6-8a74-e15675d5a5bd_default_hello-kairos4-artifacts$ sudo sgdisk -p  hello-kairos4.raw
Disk hello-kairos4.raw: 4374528 sectors, 2.1 GiB
Sector size (logical): 512 bytes
Disk identifier (GUID): 144A537B-9B38-4AE3-BAB5-DF6C85697027
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 34, last usable sector is 4374494
Partitions will be aligned on 2048-sector boundaries
Total free space is 4029 sectors (2.0 MiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048            6143   2.0 MiB     EF02  legacy
   2            6144           47103   20.0 MiB    EF00  UEFI
   3           47104          178175   64.0 MiB    8300  oem
   4          178176         4372479   2.0 GiB     8300  root
```

**Comment by Itxaka** [comment] 2023-07-31 13:49
ummm.... master is installing the rc-1 of the agent, seems it doesnt understand that 2.2.0 is final vs 2.2.0-rc1.....

This is why the reset is failing, that version is broken

**Comment by Itxaka** [comment] 2023-07-31 13:56
yep, it was missing a repo bump. Once https://github.com/kairos-io/kairos/actions/runs/5715535216/job/15485074135 finishes, new latest images will be pushed and you can try to rebuild and test those @nano2007 they should work!

**Comment by nano2007** [comment] 2023-08-01 11:14
Thanks a lot @Itxaka . Does the fix apply to opensuse-leap only or will work for other flavours too (specifically interested in debian)?

**Comment by Itxaka** [comment] 2023-08-01 11:20
> Thanks a lot @Itxaka . Does the fix apply to opensuse-leap only or will work for other flavours too (specifically interested in debian)?

Everything should be fixed, the repos are distro independent so new versions apply to all flavours!

**Comment by nano2007** [comment] 2023-08-01 11:31
Awesome @Itxaka. For the specific issue with debian (need to add rd.live.overlay.overlayfs to kernel command line for the cloudimage to work), I will create another ticket.

**Comment by nano2007** [comment] 2023-08-02 04:59
There is already a ticket for the debian issue: https://github.com/kairos-io/kairos/issues/1621

**Comment by nano2007** [comment] 2023-08-02 05:25
@Itxaka any way to get the builds now for some testing?

**Comment by Itxaka** [comment] 2023-08-02 08:08
@nano2007 if you rebuild with the example yaml given in the docs you should get the fixed one, as that uses 

```
imageName: "quay.io/kairos/core-opensuse-leap:latest"
```

and tht should be already updated to point to the master build!

**Comment by nano2007** [comment] 2023-08-02 09:24
@Itxaka I tried it this morning and still got the same error (kairos-agent exited with 2). I will try it once more and attach the logs.

**Comment by nano2007** [comment] 2023-08-02 11:11
I tried creating another image and there is no change in behaviour. Here is the /etc/os-release output.

```
NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
KAIROS_NAME="kairos-core-opensuse-leap"
KAIROS_VERSION="v2.3.0-34-g19f3c7a"
KAIROS_ID="kairos"
KAIROS_ID_LIKE="kairos-core-opensuse-leap"
KAIROS_VERSION_ID="v2.3.0-34-g19f3c7a"
KAIROS_PRETTY_NAME="kairos-core-opensuse-leap v2.3.0-34-g19f3c7a"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/core-opensuse-leap"
KAIROS_IMAGE_LABEL="latest"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_VARIANT="core"
KAIROS_FLAVOR="opensuse-leap"
```

**Comment by nano2007** [comment] 2023-08-02 11:13
@Itxaka attached are the logs system_Aug2.log. 
[system_Aug2.log](https://github.com/kairos-io/kairos/files/12239392/system_Aug2.log)

**Comment by Itxaka** [comment] 2023-08-02 11:56
crap, that one is built from 3 hours ago so it definitevely should work.

@nano2007 let me retest this again locally!

**Comment by Itxaka** [comment] 2023-08-02 14:11
umm, Im seeing this `reset Aborted` message in the logs, that would happen if you have exited the reset instead of waiting...not sure why

```
t[1373]: Reset aborted
t[1373]: panic: nil
t[1373]: goroutine 64 [running]:
t[1373]: github.com/kairos-io/kairos-agent/v2/internal/agent.Reset.func1()
t[1373]:         /go/src/github.com/kairos-io/kairos-agent/internal/agent/reset>
t[1373]: created by github.com/kairos-io/kairos-agent/v2/internal/agent.Reset
t[1373]:         /go/src/github.com/kairos-io/kairos-agent/internal/agent/reset>
t[1373]: : failed to run kairos-agent reset && \
t[1373]: touch /usr/local/.deployed && \
t[1373]: reboot
```

**Comment by nano2007** [comment] 2023-08-02 14:26
This is the same error as last log I had attached and you had quoted right? : https://github.com/kairos-io/kairos/issues/1664#issuecomment-1658192195

I admit I do not know enough about kairos-agent works, but if I try to run it without attaching to a tty, I think it throws the same error @Itxaka 

For example, on running "nohup kairos-agent reset":
```

┌────────────────────────────────────────────────────────────────────┐
| Welcome to kairos!                                                 |
| The node will automatically reset its state in a few.              |
|                                                                    |
| Press any key to abort this process. To restart run 'kairos reset'.|
|                                                                    |
| Starting in 60 seconds...                                          |
└──────────────────────────────────────────────────────────── Reset ─┘
Reset aborted
panic: nil

goroutine 25 [running]:
github.com/kairos-io/kairos-agent/v2/internal/agent.Reset.func1()
	/go/src/github.com/kairos-io/kairos-agent/internal/agent/reset.go:49 +0xae
created by github.com/kairos-io/kairos-agent/v2/internal/agent.Reset
	/go/src/github.com/kairos-io/kairos-agent/internal/agent/reset.go:38 +0xfc


```

**Comment by nano2007** [comment] 2023-08-02 15:11
@Itxaka what does the Getty(1) call do when run ?

```
		utils.Prompt("") //nolint:errcheck
		// give tty1 back
		svc, err := machine.Getty(1)
		if err == nil {
			svc.Start() //nolint:errcheck
		}
```

**Comment by nano2007** [comment] 2023-08-02 17:27
> it should create a service with `ExecStart=tty1` on it so it can start it on the lines after. I think that was so it takes over the current tty where we run the install. Maybe on automated resets we should not do that as it can break the reset?

Yes, that makes sense. It almost looks like the automated reset would need to:

1. bypass starting the Getty(1) service
2. put agent in fast mode (without needing fast=true in /etc/kairos/agent.yaml as there is no tty and no way to abort)
3. skip the automatic rebooting, so that the boot stage can mark reset as completed etc.

A new flag (no-tty or something similar), would be good.

**Comment by Itxaka** [comment] 2023-08-03 08:19
@nano2007 currently on testing https://github.com/kairos-io/kairos-agent/pull/110

**Comment by Itxaka** [comment] 2023-08-03 08:53
can confirm that with that branch built into a raw image, the reset works as expected from yip. 

The unattended flag sets fast and it doesnt reset automatically unless you set the --reboot flag.

What Im not certain about is the sentinel file and what is it used for, I guess to avoid rebooting on recovery and triggering that again, so the touch + manual reboot may be still needed in the cloud config

**Comment by nano2007** [comment] 2023-08-03 09:37
Thanks @Itxaka 👍

**Closed** 2023-08-07 08:16 UTC
Labels: bug
