### ISSUE TITLE
Cleanup Disk Partitions

### ISSUE THREAD

**Issue by 3pings** [kairos-io/kairos#951] opened 2023-02-23 15:47 UTC
**Kairos version:**
NAME="kairos-core-opensuse-leap"
VERSION="v1.5.0"
ID="kairos"
ID_LIKE="kairos-core-opensuse-leap"
VERSION_ID="v1.5.0"
PRETTY_NAME="kairos-core-opensuse-leap v1.5.0"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
HOME_URL="https://github.com/kairos-io/kairos"
IMAGE_REPO="quay.io/kairos/core-opensuse-leap"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/kairos"
VARIANT="core"
FLAVOR="opensuse-leap

**CPU architecture, OS, and Version:**
Linux edge-d83a7e13ebdd99de453d48210b330b96 5.14.21-150400.24.41-default #1 SMP PREEMPT_DYNAMIC Fri Jan 13 08:55:22 UTC 2023 (1d4442d) x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
Installing over a previously installed disk (reflashing) errors with "Failed creating new partition table: Error: Partitions(s) on /dev/nvme0n1 are being used."
Error: 1 error occurred:
            * exit status 1
            
exit status 1

The disk should be wiped clean and partitions deleted before attempting the install.

**To Reproduce**
Install Kairos completely, reinstall onto the same disk.

**Expected behavior**
Installation should erase the disk and partitions before attempting to install.

**Comment by Itxaka** [comment] 2023-02-23 16:38
dupe of https://github.com/kairos-io/kairos/issues/499

**Closed** 2023-02-23 16:38 UTC
Labels: bug
