### ISSUE TITLE
:bug: stages commands getting skipped if present on multiple cloud init files

### ISSUE THREAD

**Issue by kpiyush17** [kairos-io/kairos#1676] opened 2023-08-03 10:07 UTC
**Kairos version:**
```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
KAIROS_NAME="kairos-core-ubuntu-22-lts"
KAIROS_VERSION="v2.3.1"
KAIROS_ID="kairos"
KAIROS_ID_LIKE="kairos-core-ubuntu-22-lts"
KAIROS_VERSION_ID="v2.3.1"
KAIROS_PRETTY_NAME="kairos-core-ubuntu-22-lts v2.3.1"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/core-ubuntu-22-lts"
KAIROS_IMAGE_LABEL="latest"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_VARIANT="core"
KAIROS_FLAVOR="ubuntu-22-lts"
```

**CPU architecture, OS, and Version:**
```
edge-b2263842120d39bd52240124271196c4 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Describe the bug**
we have two files in /oem:
80_stylus.yaml
```
  initramfs:
  - commands:
    - mkdir -p /opt/testing-80-stylus
```

85_cluster_config.yaml
```
  initramfs:
  - commands:
    - mkdir -p /opt/testing-85-cluster-config
```
testing-80-stylus is getting created every time but testing-85-cluster-config is only getting created when I add a name flag.
So, if I add a name flag like this:
```
  initramfs:
  - commands:
    - mkdir -p /opt/testing-85-cluster-config
    name: "creating 85"
```
and the folder got created.

On contrast,  I rename the 85_cluster_config.yaml to 75_cluster_config.yaml with following contents:
```
  initramfs:
  - commands:
    - mkdir -p /opt/testing-75-cluster-config
```
and this time testing-75-cluster-config directory got created but testing-80-stylus did not regardless of the name. 
It seems the file which is getting read first got executed first while the other command in the same stage is getting skipped.

Kairos-agent version: v2.1.12

**Expected behavior**

Both initramfs commands should get executed regardless of order.

**Comment by mauromorales** [comment] 2023-08-03 11:15
If I use the simplified examples of configs given here, it seems to work correctly for me:

```
kairos@localhost:~$ cat /oem/8*
#cloud-config
stages:
    initramfs:
    - commands:
      - mkdir -p /opt/testing-80-stylus
#cloud-config
stages:
    initramfs:
    - commands:
      - mkdir -p /opt/testing-85-cluster-config

```

results:
```
kairos@localhost:~$ ls /opt/
testing-80-stylus  testing-85-cluster-config
```

**Comment by mauromorales** [comment] 2023-08-03 11:24
I went in and put one of the full examples given on Slack, but still working for me:

```
kairos@localhost:~$ cat /oem/8*
#cloud-config
stages:
    initramfs:
    - commands:
      - mkdir -p /opt/testing-80-stylus-v2
#cloud-config
stages:
  initramfs:
  - commands:
    - mkdir -p /opt/testing-85-cluster-config-v2
  - users:
      spectro:
        name: spectro
        ssh_authorized_keys:
        - ssh-rsa 
            xxxxxxxxxxxx
        homedir: /home/spectro
        groups:
        - admin
```

output:
```
kairos@localhost:~$ ls /opt/
testing-80-stylus  testing-80-stylus-v2  testing-85-cluster-config  testing-85-cluster-config-v2
```

@kpiyush17 could you share the full config? (if there's anything sensitive maybe just xxxxx it, or pass via DM on Slack)

**Comment by jimmykarily** [comment] 2023-08-07 08:17
@kpiyush17 any updates on this?

**Comment by santhoshdaivajna** [comment] 2023-08-07 16:02
I was able to reproduce the issue on a node. I have shared the yaml files in /oem with @mauromorales

**Comment by mauromorales** [comment] 2023-08-08 07:07
I managed to reproduce with the full configuration. Will dig deeper and let you know what I find

**Comment by mauromorales** [comment] 2023-08-08 08:56
I haven't found the root of the problem but doing some cleanup in the configs that were sent makes it run properly.

there are a couple of cases where you have commands split in two lines, plese merge them into one:

```
- '[ -L /usr/local/bin/agent-provider-stylus ] || ln -s /opt/spectrocloud/bin/agent-provider-stylus
      /usr/local/bin/agent-provider-stylus'
```

should be:

```
- '[ -L /usr/local/bin/agent-provider-stylus ] || ln -s /opt/spectrocloud/bin/agent-provider-stylus /usr/local/bin/agent-provider-stylus'
```

And also please remove all the duplicated cases of creating the kairos user, it is created more than once in 80_stylus.yaml, more than once in 90_custom.yaml, and once in userdata.yaml

Last but not least, I'm not sure if you want to run stylus.yaml, but if you do, you need to add a `#cloud-config` prefix in the file

@santhoshdaivajna could you apply these and let me know?

**Comment by mauromorales** [comment] 2023-08-14 07:57
Putting back to incoming because I have a few things on my plate atm, will pick up again asap

**Comment by mudler** [comment] 2023-08-16 09:28
@kpiyush17 do you have a workaround or you are blocked and should we prioritize this item?

**Comment by santhoshdaivajna** [comment] 2023-08-16 11:45
@mauromorales suggested to use name in all command sub sections, we have hit some limitations with using this workaround as it will trigger notifications/repave of clusters. It would be good if this is prioritised higher!

**Comment by rsheng118** [comment] 2023-09-09 04:13
i have the same issue with other sections. for example, if i have two "write_files" section in different files, one will overwrite the other, they don't seem to be merged.

**Comment by Itxaka** [comment] 2023-09-11 14:58
This should be a yip issue, but I cant reproduce it...


```
$ cat test/*
stages:
  default:
    - commands:
      - echo "01"
stages:
  default:
    - commands:
      - echo "02"
```


```
$ yip test  
INFO[0000] yip version v1.4.1-gf9c893c6d6c2d112dba90463b8194ce740974f77 2023-09-07 13:23:56 UTC 
INFO[0000] Running stage: default                       
INFO[0000] Processing stage step ''. ( commands: 1, files: 0, ... ) 
INFO[0000] Command output: 01                           
INFO[0000] Processing stage step ''. ( commands: 1, files: 0, ... ) 
INFO[0000] Command output: 02                           
INFO[0000] Done executing stage 'default'     
```

**Comment by Itxaka** [comment] 2023-09-11 15:48
yup, upstream yip bug.

To reproduce:

Create 3 yaml files with the following content (Substitute $NUMBER for a different thing on each):

```
#cloud-config
stages:
  default:
    - commands:
      - echo "$NUMBER"
```


Like this:

```
$ cat 01.yaml 02.yaml 03.yaml 
#cloud-config
stages:
  default:
    - commands:
      - echo "01"
#cloud-config
stages:
  default:
    - commands:
      - echo "02"

#cloud-config
stages:
  default:
    - name: "caca"
      commands:
      - echo "03"
```


Run yip
```
$ yip -s default  /home/itxaka/projects/yip/test
INFO[0000] yip version v1.4.1-gf9c893c6d6c2d112dba90463b8194ce740974f77 2023-09-07 13:23:56 UTC 
INFO[0000] Running stage: default                       
INFO[0000] Processing stage step ''. ( commands: 1, files: 0, ... ) 
INFO[0000] Command output: 01                           
INFO[0000] Processing stage step ''. ( commands: 1, files: 0, ... ) 
INFO[0000] Command output: 03                           
INFO[0000] Done executing stage 'default'           
```

Or analyze:

```
$ yip -a -s default  /home/itxaka/projects/yip/test
INFO[0000] yip version v1.4.1-gf9c893c6d6c2d112dba90463b8194ce740974f77 2023-09-07 13:23:56 UTC 
INFO[0000] 1.                                           
INFO[0000]  <init> (background: false) (weak: false)    
INFO[0000] 2.                                           
INFO[0000]  <Cloud init.0> (background: false) (weak: true) 
INFO[0000] 3.                                           
INFO[0000]  <Cloud init.0.1> (background: false) (weak: true) 
```


Note that this happens somehow due to the `#cloud-config` header. If you remove the cloud-config header for all files, then it runs as expected:

```
$ yip -s default  /home/itxaka/projects/yip/test   
INFO[0000] yip version v1.4.1-gf9c893c6d6c2d112dba90463b8194ce740974f77 2023-09-07 13:23:56 UTC 
INFO[0000] Running stage: default                       
INFO[0000] Processing stage step ''. ( commands: 1, files: 0, ... ) 
INFO[0000] Command output: 01                           
INFO[0000] Processing stage step ''. ( commands: 1, files: 0, ... ) 
INFO[0000] Command output: 02                           
INFO[0000] Processing stage step ''. ( commands: 1, files: 0, ... ) 
INFO[0000] Command output: 03                           
INFO[0000] Done executing stage 'default'     
```

So somehow there is an issue with the header and yip reading the files or appending them or something.

**Comment by Itxaka** [comment] 2023-09-11 19:35
weird bug, could reproduce and sent a patch to yip :)

**Closed** 2023-09-12 06:37 UTC
Labels: bug
