### ISSUE TITLE
:seedling: Registry authentication for installations and upgrades

### ISSUE THREAD

**Issue by cristian98149** [kairos-io/kairos#1042] opened 2023-03-06 11:35 UTC
**Is your feature request related to a problem? Please describe.**

I tried to create my custom image using dockerfile and specifying the image in install.image field as specified in https://kairos.io/docs/examples/core/#getting-started. When pulling image from a public repo, everything works as expected so I tried to pull from a private repo and the following error occurred:
![image](https://user-images.githubusercontent.com/47886306/223098867-cf1870d7-a261-45ff-a29e-21cef6ce3f3e.png)

As expected there is an authorization issue because no authentication is provided before pulling the image.

**Describe the solution you'd like**

Provide a way to docker login before pulling image.

**Comment by mudler** [comment] 2023-03-06 11:37
Hi @cristian98149 thanks for filing up an issue!

This looks a dup of #932, are you using the image for the installation or for the upgrade?

**Comment by cristian98149** [comment] 2023-03-06 12:57
Hi @mudler,
sorry I didn't see that dup.

Currently I'm using image for installation.

Thank you.

**Comment by mudler** [comment] 2023-07-10 08:09
since we merged the `elemental-cli` to the `kairos-agent`, now we miss exposing args for authentication also during upgrades (which is a regression). moving the scope of this card to cover both as we need just to find a way to expose that to the user.

**Comment by mudler** [comment] 2023-07-17 08:35
Note from planning: we should test with docker-style credentials (with the config.json).

**Comment by Itxaka** [comment] 2023-08-08 09:05
Install works with docker creds under /root/.docker/config.json


```
localhost:~ # cat /root/.docker/config.json 
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth":  "xxxxxxxxx"
		}
	}
}

```

```
DEBU[2023-08-08T09:03:04Z] Mounting image COS_ACTIVE                    
DEBU[2023-08-08T09:03:04Z] Running cmd: 'losetup --show -f /run/cos/state/cOS/active.img' 
INFO[2023-08-08T09:03:04Z] Copying itxaka/private:opensuse-leap source... 
INFO[2023-08-08T09:03:22Z] Finished copying itxaka/private:opensuse-leap into /run/cos/active 
INFO[2023-08-08T09:03:22Z] List of cloud inits to copy: [/tmp/kairos-install-config-xxx.yaml684703264] 
INFO[2023-08-08T09:03:22Z] Starting copying cloud config file /tmp/kairos-install-config-xxx.yaml684703264 to /run/cos/oem/90_custom.yaml 
```

**Comment by Itxaka** [comment] 2023-08-08 09:06
Removing the config results in an auth error:

```
1 error occurred:
	* GET https://index.docker.io/v2/itxaka/private/manifests/opensuse-leap: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:itxaka/private Type:repository]]
```

**Comment by Itxaka** [comment] 2023-08-08 09:11
Saving the config in `${XDG_RUNTIME_DIR}/containers/auth.json` also works

**Comment by Itxaka** [comment] 2023-08-08 09:23
Passing the env var `DOCKER_CONFIG=/PATH/TO/DIR/WITH/CONFIG/` works as well!

**Comment by Itxaka** [comment] 2023-08-08 09:47
setting the env in the cloud-config also works with this patch: https://github.com/kairos-io/kairos-agent/pull/124

so you can set it to a config in a different place via cc

```
#cloud-config

install:
 device: "auto"
 auto: true
 image: "docker:itxaka/private:opensuse-leap"
 env:
 - DOCKER_CONFIG=/tmp/docker/
```

**Comment by Itxaka** [comment] 2023-08-08 09:50
same thing during upgrade, all scenarios covered.

**Closed** 2023-08-08 16:51 UTC
Labels: enhancement, area/agent, lane/ux, MVP
