### ISSUE TITLE
kairos upgrade is broken in recovery

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1751] opened 2023-08-21 13:41 UTC
**Kairos version:**
v2.3.2

**CPU architecture, OS, and Version:**
Jetson orin

**Describe the bug**
Can't upgrade the recovery image from recovery

**To Reproduce**
- Follow https://kairos.io/docs/reference/reset/, boot into recovery instead (no state reset)
- Download manually https://github.com/kairos-io/kairos-agent/releases/tag/v2.2.7
- run `sudo kairos-agent upgrade --recovery --image <IMAGE>`
- or run `sudo kairos-agent upgrade --image <IMAGE`

**Expected behavior**

**Logs**
```
INFO[2023-08-21T13:32:35Z] Running stage: before-upgrade.after          
INFO[2023-08-21T13:32:35Z] Done executing stage 'before-upgrade.after'  
INFO[2023-08-21T13:32:35Z] deploying image quay.io/mudler/tests:orin-nvidia to /run/initramfs/cos-state/cOS/transition.img 
INFO[2023-08-21T13:32:35Z] Creating file system image /run/initramfs/cos-state/cOS/transition.img with size 0Mb 
DEBU[2023-08-21T13:32:35Z] Running cmd: 'mkfs.ext2 -L COS_SYSTEM /run/initramfs/cos-state/cOS/transition.img' 
ERRO[2023-08-21T13:32:35Z] Failed deploying image to file '/run/initramfs/cos-state/cOS/transition.img': exit status 1 
```

**Additional context**
Faced this while working on https://github.com/kairos-io/kairos/issues/1723

**Comment by mudler** [comment] 2023-08-21 13:48
this seems to affect all flavors - not only ARM

**Comment by Itxaka** [comment] 2023-08-21 14:54
agent recovery upgrade fixed on https://github.com/kairos-io/kairos-agent/pull/132 released on https://github.com/kairos-io/kairos-agent/releases/tag/v2.2.8

**Comment by Itxaka** [comment] 2023-08-21 14:55
manually confirmed on x86 master build of kairos with agent v2.2.8
 - Install
 - boot from recovery
 - upgrade recovery with `kairos-agent upgrade --recovery`
 - upgraded active with `kairos-agent upgrade`
 - rebooted into active: OK
 - rebooted into passive: OK
 - rebooted into recovery: OK

**Comment by mauromorales** [comment] 2023-08-24 10:09
I was testing this on the latest alpha, will test with 2.3.2 now

**Comment by mauromorales** [comment] 2023-08-24 13:14
Under 2.3.2 I get the following error:

```
kairos@cos-recovery:~$ sudo ./kairos-agent upgrade --recovery --image=quay.io/kairos/core-ubuntu:v2.3.2
--image flag is deprecated, please use --source
WARNING: jsonschema: '' does not validate with file:///home/kairos/schema.json#/required: missing properties: 'users'
INFO[2023-08-24T13:13:04Z] kairos-agent version v2.2.8
WARN[2023-08-24T13:13:04Z] failed reading installation state: open /run/initramfs/cos-state/state.yaml: no such file or directory
179:3

Reading udevdata of device: /run/udev/data/b179:0
179:3

Reading udevdata of device: /run/udev/data/b179:0
INFO[2023-08-24T13:13:05Z] Setting image size to 2917Mb
INFO[2023-08-24T13:13:05Z] Applying 'before-upgrade' hook
INFO[2023-08-24T13:13:05Z] Running before-upgrade hook
INFO[2023-08-24T13:13:05Z] Running stage: before-upgrade.before
INFO[2023-08-24T13:13:05Z] Done executing stage 'before-upgrade.before'
INFO[2023-08-24T13:13:05Z] Running stage: before-upgrade
INFO[2023-08-24T13:13:05Z] Done executing stage 'before-upgrade'
INFO[2023-08-24T13:13:05Z] Running stage: before-upgrade.after
INFO[2023-08-24T13:13:05Z] Done executing stage 'before-upgrade.after'
INFO[2023-08-24T13:13:05Z] Running stage: before-upgrade.before
INFO[2023-08-24T13:13:05Z] Done executing stage 'before-upgrade.before'
INFO[2023-08-24T13:13:05Z] Running stage: before-upgrade
INFO[2023-08-24T13:13:05Z] Done executing stage 'before-upgrade'
INFO[2023-08-24T13:13:05Z] Running stage: before-upgrade.after
INFO[2023-08-24T13:13:05Z] Done executing stage 'before-upgrade.after'
INFO[2023-08-24T13:13:05Z] deploying image quay.io/kairos/core-ubuntu:v2.3.2 to /run/cos/recovery/cOS/transition.img
INFO[2023-08-24T13:13:05Z] Creating file system image /run/cos/recovery/cOS/transition.img with size 2917Mb
ERRO[2023-08-24T13:13:05Z] Failed deploying image to file '/run/cos/recovery/cOS/transition.img': open /run/cos/recovery/cOS/transition.img: read-only file system
1 error occurred:
	* open /run/cos/recovery/cOS/transition.img: read-only file system
```

**Comment by mauromorales** [comment] 2023-08-24 14:23
Ok, I guess I was doing this wrong, and I was supposed to upgrade the recovery from the active partition because then it works as expected 🎉

**Comment by mauromorales** [comment] 2023-08-24 14:38
Also I think some files got corrupted in the process because I see the following errors all the time now

![2CE05A44-B6EB-465C-B431-D4E836A918EC_1_102_o](https://github.com/kairos-io/kairos/assets/433958/d75ec6a5-feee-41b5-a4a5-ece96678dfc5)

**Comment by mauromorales** [comment] 2023-08-24 14:40
If I try to upgrade A from recovery, I'm getting this error, maybe I got banned for using quay too often 🤣 

```
kairos@cos-recovery:~$ sudo ./kairos-agent upgrade --image=quay.io/kairos/core-ubuntu-arm-rpi:v2.3.2
--image flag is deprecated, please use --source
WARNING: jsonschema: '' does not validate with file:///home/kairos/schema.json#/required: missing properties: 'users'
INFO[2023-03-20T14:25:52Z] kairos-agent version v2.2.8
179:3

Reading udevdata of device: /run/udev/data/b179:0
179:3

Reading udevdata of device: /run/udev/data/b179:0
WARN[2023-03-20T14:26:05Z] Failed to infer size for images: Get "https://quay.io/v2/": dial tcp: lookup quay.io on [::1]:53: read udp [::1]:42602->[::1]:53: read: connection refused
INFO[2023-03-20T14:26:05Z] Applying 'before-upgrade' hook
INFO[2023-03-20T14:26:05Z] Running before-upgrade hook
INFO[2023-03-20T14:26:05Z] Running stage: before-upgrade.before
INFO[2023-03-20T14:26:05Z] Done executing stage 'before-upgrade.before'
INFO[2023-03-20T14:26:05Z] Running stage: before-upgrade
INFO[2023-03-20T14:26:05Z] Done executing stage 'before-upgrade'
INFO[2023-03-20T14:26:05Z] Running stage: before-upgrade.after
INFO[2023-03-20T14:26:05Z] Done executing stage 'before-upgrade.after'
INFO[2023-03-20T14:26:05Z] Running stage: before-upgrade.before
INFO[2023-03-20T14:26:05Z] Done executing stage 'before-upgrade.before'
INFO[2023-03-20T14:26:05Z] Running stage: before-upgrade
INFO[2023-03-20T14:26:05Z] Done executing stage 'before-upgrade'
INFO[2023-03-20T14:26:05Z] Running stage: before-upgrade.after
INFO[2023-03-20T14:26:05Z] Done executing stage 'before-upgrade.after'
INFO[2023-03-20T14:26:05Z] deploying image quay.io/kairos/core-ubuntu-arm-rpi:v2.3.2 to /run/cos/state/cOS/transition.img
INFO[2023-03-20T14:26:05Z] Creating file system image /run/cos/state/cOS/transition.img with size 3072Mb
INFO[2023-03-20T14:26:06Z] Copying quay.io/kairos/core-ubuntu-arm-rpi:v2.3.2 source to /run/cos/transition
ERRO[2023-03-20T14:26:19Z] Failed deploying image to file '/run/cos/state/cOS/transition.img': Get "https://quay.io/v2/": dial tcp: lookup quay.io on [::1]:53: read udp [::1]:57359->[::1]:53: read: connection refused
1 error occurred:
	* Get "https://quay.io/v2/": dial tcp: lookup quay.io on [::1]:53: read udp [::1]:57359->[::1]:53: read: connection refused
```

**Comment by mauromorales** [comment] 2023-08-24 17:44
Tried to upgrade recovery again in case it was a problem with the SD card, but this time it went even worse. The upgrade finishes successfuly but when I start on recovery I see an error saying:

```
Failed to execute /sbin/init
Failed to execute fallback shell
```

**Comment by mauromorales** [comment] 2023-08-25 10:22
Ok I finally got a positive run with opensuse-leap v2.4.0-alpha3 ... upgrade active and upgrade recovery both worked successfuly ... will give ubuntu one last shot just to validate if I missed something or otherwise open an issue just for ubuntu

**Comment by mauromorales** [comment] 2023-08-25 15:06
I keep encountering issues with Ubuntu, this time the upgrade finished, and I was able to log in, but I'm not able to ssh in. Looking into it, the service was not run because the link under `/etc/systemd/system` is present but the file under `/lib/systemd` is not, actually the full directory is missing.

**Comment by Itxaka** [comment] 2023-09-04 10:40
Upgrade seems to go ok but when unounting errors appear:


```
DEBU[2023-09-04T10:37:06Z] Mounting partition COS_STATE                 
DEBU[2023-09-04T10:37:06Z] Mounting partition COS_RECOVERY              
DEBU[2023-09-04T10:37:06Z] mounting persistent partition                
DEBU[2023-09-04T10:37:06Z] Mounting partition COS_PERSISTENT            
INFO[2023-09-04T10:37:06Z] Applying 'before-upgrade' hook               
INFO[2023-09-04T10:37:06Z] Running before-upgrade hook                  
DEBU[2023-09-04T10:37:06Z] Cloud-init paths set to [/system/oem /oem/ /usr/local/cloud-config/] 
INFO[2023-09-04T10:37:06Z] Running stage: before-upgrade.before         
INFO[2023-09-04T10:37:06Z] Done executing stage 'before-upgrade.before' 
INFO[2023-09-04T10:37:06Z] Running stage: before-upgrade                
INFO[2023-09-04T10:37:06Z] Done executing stage 'before-upgrade'        
INFO[2023-09-04T10:37:06Z] Running stage: before-upgrade.after          
INFO[2023-09-04T10:37:06Z] Done executing stage 'before-upgrade.after'  
INFO[2023-09-04T10:37:06Z] Running stage: before-upgrade.before         
INFO[2023-09-04T10:37:06Z] Done executing stage 'before-upgrade.before' 
INFO[2023-09-04T10:37:06Z] Running stage: before-upgrade                
INFO[2023-09-04T10:37:06Z] Done executing stage 'before-upgrade'        
INFO[2023-09-04T10:37:06Z] Running stage: before-upgrade.after          
INFO[2023-09-04T10:37:06Z] Done executing stage 'before-upgrade.after'  
INFO[2023-09-04T10:37:06Z] deploying image ttl.sh/itxaka:rpi64 to /run/cos/state/cOS/transition.img 
INFO[2023-09-04T10:37:06Z] Creating file system image /run/cos/state/cOS/transition.img with size 2594Mb 
DEBU[2023-09-04T10:37:06Z] Running cmd: 'mkfs.ext2 -L COS_ACTIVE /run/cos/state/cOS/transition.img' 
DEBU[2023-09-04T10:37:06Z] Mounting image COS_ACTIVE                    
DEBU[2023-09-04T10:37:06Z] Running cmd: 'losetup --show -f /run/cos/state/cOS/transition.img' 
INFO[2023-09-04T10:37:06Z] Copying ttl.sh/itxaka:rpi64 source to /run/cos/transition 
INFO[2023-09-04T10:39:46Z] Finished copying ttl.sh/itxaka:rpi64 into /run/cos/transition 
DEBU[2023-09-04T10:39:47Z] No files relabelling as SELinux utilities are not found 
DEBU[2023-09-04T10:39:47Z] Unmounting /run/cos/transition/usr/local from chroot 
DEBU[2023-09-04T10:39:47Z] Unmounting /run/cos/transition/oem from chroot 
DEBU[2023-09-04T10:39:47Z] Unmounting /run/cos/transition/sys from chroot 
DEBU[2023-09-04T10:39:47Z] Unmounting /run/cos/transition/proc from chroot 
DEBU[2023-09-04T10:39:47Z] Unmounting /run/cos/transition/dev/pts from chroot 
DEBU[2023-09-04T10:39:47Z] Unmounting /run/cos/transition/dev from chroot 
INFO[2023-09-04T10:39:47Z] Applying 'after-upgrade-chroot' hook         
INFO[2023-09-04T10:39:47Z] Running after-upgrade-chroot hook            
DEBU[2023-09-04T10:39:47Z] Cloud-init paths set to [/system/oem /oem/ /usr/local/cloud-config/] 
INFO[2023-09-04T10:39:47Z] Running stage: after-upgrade-chroot.before   
INFO[2023-09-04T10:39:47Z] Done executing stage 'after-upgrade-chroot.before' 
INFO[2023-09-04T10:39:47Z] Running stage: after-upgrade-chroot          
INFO[2023-09-04T10:39:47Z] Done executing stage 'after-upgrade-chroot'  
INFO[2023-09-04T10:39:47Z] Running stage: after-upgrade-chroot.after    
INFO[2023-09-04T10:39:47Z] Done executing stage 'after-upgrade-chroot.after' 
INFO[2023-09-04T10:39:47Z] Running stage: after-upgrade-chroot.before   
INFO[2023-09-04T10:39:47Z] Done executing stage 'after-upgrade-chroot.before' 
INFO[2023-09-04T10:39:47Z] Running stage: after-upgrade-chroot          
INFO[2023-09-04T10:39:47Z] Done executing stage 'after-upgrade-chroot'  
INFO[2023-09-04T10:39:47Z] Running stage: after-upgrade-chroot.after    
INFO[2023-09-04T10:39:47Z] Done executing stage 'after-upgrade-chroot.after' 
DEBU[2023-09-04T10:39:47Z] Unmounting /run/cos/transition/usr/local from chroot 
DEBU[2023-09-04T10:39:47Z] Unmounting /run/cos/transition/oem from chroot 
DEBU[2023-09-04T10:39:47Z] Unmounting /run/cos/transition/sys from chroot 
DEBU[2023-09-04T10:39:47Z] Unmounting /run/cos/transition/proc from chroot 
DEBU[2023-09-04T10:39:47Z] Unmounting /run/cos/transition/dev/pts from chroot 
DEBU[2023-09-04T10:39:47Z] Unmounting /run/cos/transition/dev from chroot 
INFO[2023-09-04T10:39:47Z] rebranding                                   
DEBU[2023-09-04T10:39:47Z] Unmounting image COS_ACTIVE                  
[  368.590557] loop: Write error at byte offset 90558464, length 4096.
[  368.597065] I/O error, dev loop1, sector 176872 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 2
[  368.601187] loop: Write error at byte offset 90554368, length 4096.
[  368.612374] I/O error, dev loop1, sector 176864 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 2
[  368.612384] Buffer I/O error on device loop1, logical block 22109
[  368.613210] loop: Write error at byte offset 90550272, length 4096.
[  368.613234] I/O error, dev loop1, sector 176856 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 2
[  368.613257] Buffer I/O error on device loop1, logical block 22107
[  368.613355] loop: Write error at byte offset 90546176, length 4096.
[  368.613374] I/O error, dev loop1, sector 176848 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 2
[  368.613395] Buffer I/O error on device loop1, logical block 22106
[  368.613472] loop: Write error at byte offset 58511360, length 4096.
[  368.613491] I/O error, dev loop1, sector 114280 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 2
[  368.613511] Buffer I/O error on device loop1, logical block 14285
[  368.613588] loop: Write error at byte offset 90542080, length 4096.
[  368.613607] I/O error, dev loop1, sector 176840 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 2
[  368.613626] Buffer I/O error on device loop1, logical block 22105
[  368.613702] loop: Write error at byte offset 90537984, length 4096.
[  368.613720] I/O error, dev loop1, sector 176832 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 2
[  368.613740] Buffer I/O error on device loop1, logical block 22104
[  368.613814] loop: Write error at byte offset 90533888, length 4096.
[  368.613832] I/O error, dev loop1, sector 176824 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 2
[  368.613851] Buffer I/O error on device loop1, logical block 22103
[  368.613926] loop: Write error at byte offset 90529792, length 4096.
[  368.613945] I/O error, dev loop1, sector 176816 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 2
[  368.613964] Buffer I/O error on device loop1, logical block 22102
[  368.614038] loop: Write error at byte offset 90525696, length 4096.
[  368.614056] I/O error, dev loop1, sector 176808 op 0x1:(WRITE) flags 0x0 phys_seg 1 prio class 2
[  368.614075] Buffer I/O error on device loop1, logical block 22101
[  368.614176] Buffer I/O error on device loop1, logical block 14301
[  370.051853] Buffer I/O error on dev loop1, logical block 1255, lost async page write
[  370.059851] Buffer I/O error on dev loop1, logical block 1254, lost async page write
[  370.061223] Buffer I/O error on dev loop1, logical block 1253, lost async page write
[  370.061824] Buffer I/O error on dev loop1, logical block 1252, lost async page write
[  370.061931] Buffer I/O error on dev loop1, logical block 1251, lost async page write
[  370.062025] Buffer I/O error on dev loop1, logical block 1250, lost async page write
[  370.062118] Buffer I/O error on dev loop1, logical block 1249, lost async page write
[  370.062211] Buffer I/O error on dev loop1, logical block 1248, lost async page write
[  370.062319] Buffer I/O error on dev loop1, logical block 1199, lost async page write
[  370.062412] Buffer I/O error on dev loop1, logical block 1198, lost async page write
```

**Comment by Itxaka** [comment] 2023-09-04 10:42
feels like maybe size calculation is wrong somehow and it cannot fully write the whole image maybe?

Weird that it would calculate the size properly for other flavors but not for ubuntu...

**Comment by Itxaka** [comment] 2023-09-04 10:43
or maybe its too slow to write? Gonna check setting the image size manually to see

**Comment by Itxaka** [comment] 2023-09-04 10:45
it is true that the size of the old active.img is bigger than the newer active.img:


```
root@cos-recovery:/tmp/state/cOS# ls -lh
total 4.3G
-rw-r--r--  1 root root 2.6G Sep  4 10:41 active.img
-rw-r--r--. 1 root root 2.7G Sep  4 10:41 passive.img
```

This is after upgrade, so passive.img is the backup of active.img and active.img is the upgraded image...

**Comment by Itxaka** [comment] 2023-09-04 13:09
Looks like this goes away by increasing the size of the state partition+image size. As this is predefined in the build pipeline it seems like there is not enough space to create the needed image and it fails to copy stuff onto it.

State partition default is 6900, image size is 2700. So we got active + passive + transition image, which is a total of 8100.
Images can be created with no issue (you can have a 100Gb image in a 10Gb partition) as they are sparse by default, so they dont really occupy space. But once you mount it and fille it with the upgrade data, they rach the partition size limit and fail to copy the full upgrade source, turning into errors and missing files in them.

This is why only ubuntu is affected, as its the biggest flavor of them all.

**Closed** 2023-09-05 12:01 UTC
Labels: bug, prio: high
