### ISSUE TITLE
OS-builder fails to generate ISO when registry in docker-image contains port

### ISSUE THREAD

**Issue by rishi-anand** [kairos-io/kairos#1294] opened 2023-04-14 05:28 UTC
**Kairos version:**

Issue in `quay.io/kairos/osbuilder-tools:v0.3.3`

**CPU architecture, OS, and Version:**

NA

**Describe the bug**

I am trying to use os-builder to generate the ISO from custom installer image. If the provided image contains port number then command execution fails with below error.

![image](https://user-images.githubusercontent.com/9067666/231948951-34b80fc7-17e8-4be4-b28c-637f873894a2.png)

```
docker run -v /root/work/playground/test/output:/cOS -v /var/run/docker.sock:/var/run/docker.sock -i --rm quay.io/kairos/osbuilder-tools:v0.3.3 --name spectro-edge-installer --debug build-iso --date=false 10.10.244.9:8000/spectro-images/spectro-edge-installer:v3.3.2-alpha2 --local --overlay-iso /cOS/overlay/files-iso --output /cOS/
```
**To Reproduce**

Building ISO with image in format `registry:port/repo/image:tag` will fail

**Expected behavior**

ISO should get created with the provided image.

**Logs**

```
> docker run -v /root/work/playground/test/output:/cOS -v /var/run/docker.sock:/var/run/docker.sock -i --rm quay.io/kairos/osbuilder-tools:v0.3.3 --name spectro-edge-installer --debug build-iso --date=false 10.10.244.9:8000/spectro-images/spectro-edge-installer:v3.3.2-alpha2 --local --overlay-iso /cOS/overlay/files-iso --output /cOS/
+ elemental --config-dir /config --name spectro-edge-installer --debug build-iso --date=false 10.10.244.9:8000/spectro-images/spectro-edge-installer:v3.3.2-alpha2 --local --overlay-iso /cOS/overlay/files-iso --output /cOS/
DEBU[2023-04-14T05:20:32Z] Starting elemental version v0.0.1 on commit b549edafa8430967b3cb61b41a50deb792395b4f
DEBU[2023-04-14T05:20:32Z] Full config loaded: &v1.BuildConfig{
  Date: false,
  Name: "spectro-edge-installer",
  OutDir: "/cOS/",
  Config: v1.Config{
    Logger: &v1.logrusWrapper{ // p0
      Logger: &logrus.Logger{
        Out: &os.File{},
        Hooks: logrus.LevelHooks{},
        Formatter: &logrus.TextFormatter{
          ForceColors: true,
          DisableColors: false,
          ForceQuote: false,
          DisableQuote: false,
          EnvironmentOverrideColors: false,
          DisableTimestamp: false,
          FullTimestamp: true,
          TimestampFormat: "",
          DisableSorting: false,
          SortingFunc: ,
          DisableLevelTruncation: false,
          PadLevelText: false,
          QuoteEmptyFields: false,
          FieldMap: logrus.FieldMap(nil), // p1
          CallerPrettyfier: ,
        },
        ReportCaller: false,
        Level: 5,
        ExitFunc: os.Exit,
      },
    },
    Fs: &vfs.osfs{}, // p2
    Mounter: &mount.Mounter{},
    Runner: &v1.RealRunner{ // p3
      Logger: p0,
    },
    Syscall: &v1.RealSyscall{},
    CloudInitRunner: &cloudinit.YipCloudInitRunner{},
    Luet: &luet.Luet{
      VerifyImageUnpack: false,
      TmpDir: "/tmp/elemental-3144049489",
    },
    Client: &http.Client{},
    Cosign: false,
    Verify: false,
    CosignPubKey: "",
    LocalImage: true,
    Repos: []v1.Repository{
      v1.Repository{
        Name: "cos",
        Priority: 90,
        URI: "quay.io/costoolkit/releases-green",
        Type: "docker",
        Arch: "x86_64",
        ReferenceID: "",
      },
    },
    Arch: "x86_64",
    SquashFsCompressionConfig: []string{
      "-comp",
      "gzip",
    },
    SquashFsNoCompression: false,
  },
}
DEBU[2023-04-14T05:20:32Z] Loaded LiveISO: &v1.LiveISO{
  RootFS: nil,
  UEFI: []*v1.ImageSource{
    &v1.ImageSource{},
  },
  Image: []*v1.ImageSource{
    &v1.ImageSource{},
    &v1.ImageSource{},
  },
  Label: "COS_LIVE",
  GrubEntry: "cOS",
  BootloaderInRootFs: false,
}
ERRO[2023-04-14T05:20:32Z] not a valid rootfs source image argument: 10.10.244.9:8000/spectro-images/spectro-edge-installer:v3.3.2-alpha2
>
```

**Additional context**

NA

**Comment by mudler** [comment] 2023-04-14 06:10
Nice catch! A temporary workaround would be to pull the image into a directory and specify that to it.

**Comment by mudler** [comment] 2023-04-14 07:29
elemental doesn't support image tars, it supports plain directories.

Instead of specifying a container image, you can specify a path that contains the flattened root filesystem, e.g. `dir:///path/to/the/rootfs`

so, for instance:

```
docker run -v $PWD/output:/cOS -v /var/run/docker.sock:/var/run/docker.sock -i --rm quay.io/kairos/osbuilder-tools:v0.3.3 --name spectro-edge-installer --debug build-iso --date=false dir:///cOS/ --output /cOS/
```

Note that you need to unpack the container image to the dir first.

**Comment by mudler** [comment] 2023-04-14 07:32
another (easier) way to do it is, pull the image locally with docker - tag it with another name, and run the command again by pointing to that image.

**Comment by 3pings** [comment] 2023-04-14 12:44
This is a pretty impactful issue for customer experience.  This should be prioritized to be fixed in the next release.

**Comment by mudler** [comment] 2023-04-14 14:38
> This is a pretty impactful issue for customer experience. This should be prioritized to be fixed in the next release.

I agree, but we are collecting already more impactful bugs for v2.0.1 https://github.com/kairos-io/kairos/issues/1222  - this has been there for long time already - and this is the first time it was noticed. 

Most imporantly, there is a very trivial workaround available - just pull the image locally, and tag it in the local host before using osbuilder with another name - can be implemented in a wrapper for instance, or in Auroraboot which is the UX front-end for osbuilder.

**Comment by mauromorales** [comment] 2023-04-20 13:29
@rishi-anand debugging this a little shows that the issue is raised because the URL doesn't have a scheme. It should work with if you pass here `docker://10.10.244.9:8000/spectro-images/spectro-edge-installer:v3.3.2-alpha2` or `oci://10.10.244.9:8000/spectro-images/spectro-edge-installer:v3.3.2-alpha2`. Now, if the scheme is different than these two, we would need to add it to the list of valid ones

**Comment by mauromorales** [comment] 2023-04-21 09:37
Added a PR to document this and IMO it can be closed afterwards. WDYT @paynejacob @rishi-anand ?

**Closed** 2023-04-21 12:50 UTC
Labels: bug
