### ISSUE TITLE
Missing k3s folders and files in rpi images

### ISSUE THREAD

**Issue by felixmw** [kairos-io/kairos#1847] opened 2023-09-23 13:44 UTC
**Kairos version:**
NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
KAIROS_NAME="kairos-kairos-opensuse-leap-arm-rpi"
KAIROS_VERSION="v2.4.0-k3sv1.27.3+k3s1"
KAIROS_ID="kairos"
KAIROS_ID_LIKE="kairos-kairos-opensuse-leap-arm-rpi"
KAIROS_VERSION_ID="v2.4.0-k3sv1.27.3+k3s1"
KAIROS_PRETTY_NAME="kairos-kairos-opensuse-leap-arm-rpi v2.4.0-k3sv1.27.3+k3s1"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/kairos-opensuse-leap-arm-rpi"
KAIROS_IMAGE_LABEL=""
KAIROS_GITHUB_REPO="kairos-io/provider-kairos"
KAIROS_VARIANT="kairos"
KAIROS_FLAVOR="opensuse-leap-arm-rpi"

**CPU architecture, OS, and Version:**
Linux localhost 5.14.21-150500.55.19-default #1 SMP PREEMPT_DYNAMIC Tue Aug 8 22:15:01 UTC 2023 (9908c29) aarch64 aarch64 aarch64 GNU/Linux

**Describe the bug**
I installed the current rpi images - tried both the Ubuntu and the opensuse leap versions - on a raspberry pi 4 as described her (https://kairos.io/docs/installation/raspberry/) and as I have done several times before. To setup the node I make use of Ansible playbooks.

When my playbooks failed I realized that apart from elder versions of these images several k3s related folders and their containing files are missing from the image.

The following two folders 
- /etc/rancher/k3s/
- /var/lib/rancher/k3s/

are missing and especially the following file is not part of the image:
- /etc/rancher/k3s/k3s.yaml

**To Reproduce**
Install the latest version of kairos on a raspberry pi as described here: https://kairos.io/docs/installation/raspberry/

**Expected behavior**
The listed files and folders should exist

**Logs**

**Additional context**

**Comment by jimmykarily** [comment] 2023-09-25 08:35
This issue was supposedly fixed here: https://github.com/kairos-io/packages/commit/59fabf5527028c646cf5337b4697efe913ed8907 and includedin 2.4.0 release which you seem to be using. Let's try toi reproduce, maybe we missed something.

**Comment by jimmykarily** [comment] 2023-09-25 08:37
Regarding `/etc/rancher/k3s/k3s.yaml`, I think this is a file that gets generates when k3s starts. [There is a bug](https://github.com/kairos-io/kairos/issues/1831) that prevents k3s from starting on rpi because the persistent partition is not expanded thus it's remains too small for k3s to start. Maybe that's the reason you don't see that file.

In any case, let's debug this.

**Comment by jimmykarily** [comment] 2023-09-26 07:14
I built an image from kairos `master` branch with the persistent partition expansion fix. k3s starts fine and the `/etc/rancher/k3s/` directory gets created along with the files in it.

The issues seems to be the expansion bug preventing k3s form starting and creating those files and directories. Should be fixed in the next patch release.

I'll keep this open to verify when that release is out.

**Comment by felixmw** [comment] 2023-09-26 16:13
Thanx @jimmykarily for digging into this issue. Highly appreciated. So I will wait patiently for the next patch release.

**Comment by jimmykarily** [comment] 2023-10-04 13:25
[v2.4.1 is now out](https://github.com/kairos-io/kairos/releases/tag/v2.4.1) and it fixes this issue. I'm closing this. @felixmw please re-open if you encounter any issues. Thanks for reporting.

**Closed by jimmykarily** 2023-10-04 13:25 UTC
Labels: bug, arm/rpi
