### ISSUE TITLE
recovery or reset boot options do not work on rpi 

### ISSUE THREAD

**Issue by Ognian** [kairos-io/kairos#1227] opened 2023-03-30 16:05 UTC
**Kairos version:**

NAME="kairos-opensuse-leap-arm-rpi"
VERSION="v1.6.1-k3sv1.26.1+k3s1"
ID="kairos"
ID_LIKE="kairos-opensuse-leap-arm-rpi"
VERSION_ID="v1.6.1-k3sv1.26.1+k3s1"
PRETTY_NAME="kairos-opensuse-leap-arm-rpi v1.6.1-k3sv1.26.1+k3s1"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues/new/choose"
HOME_URL="https://github.com/kairos-io/provider-kairos"
IMAGE_REPO="quay.io/kairos/kairos-opensuse-leap-arm-rpi"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/provider-kairos"
VARIANT="core"
FLAVOR="opensuse-leap"

**CPU architecture, OS, and Version:**

Linux rpi4node 5.14.21-150400.24.46-default #1 SMP PREEMPT_DYNAMIC Thu Feb 9 08:38:18 UTC 2023 (2d95137) aarch64 aarch64 aarch64 GNU/Linux

**Describe the bug**

Somehow (most likely power cut) rpi node is no more associated to the master. (maybe the random part of the node name has changed ) Then I tried to reset the node via grub menu entry. Since this was not successful I tried to get into recovery mode which was also not possible due to the below error.
 `sudo kairos-agent reset` doesn't work also...

**To Reproduce**

**Expected behavior**

**Logs**

**Additional context**

<img width="871" alt="image" src="https://user-images.githubusercontent.com/1231174/228886619-a8d5830b-63fc-48df-91e6-0692467f7ea9.png">

**Comment by jimmykarily** [comment] 2023-04-03 08:23
This is a duplicate of https://github.com/kairos-io/kairos/issues/622 . Closing this one.

**Closed by jimmykarily** 2023-04-03 08:23 UTC
Labels: bug
