### ISSUE TITLE
Factory reset is not working as described on raspberrypi

### ISSUE THREAD

**Issue by c0ffee** [kairos-io/kairos#622] opened 2023-01-09 19:16 UTC
**Kairos version:**
NAME="kairos-opensuse-arm-rpi"
VERSION="v1.4.0-k3sv1.24.9+k3s1"
ID="kairos"
ID_LIKE="kairos-opensuse-arm-rpi"
VERSION_ID="v1.4.0-k3sv1.24.9+k3s1"
PRETTY_NAME="kairos-opensuse-arm-rpi v1.4.0-k3sv1.24.9+k3s1"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues/new/choose"
HOME_URL="https://github.com/kairos-io/provider-kairos"
IMAGE_REPO="quay.io/kairos/kairos-opensuse-arm-rpi"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/provider-kairos"
VARIANT="core"
FLAVOR="opensuse"

**CPU architecture, OS, and Version:**
Linux k8s-rpi3-1 5.14.21-150400.24.38-default #1 SMP PREEMPT_DYNAMIC Fri Dec 9 09:29:22 UTC 2022 (e9c5676) aarch64 aarch64 aarch64 GNU/Linux

**Describe the bug**
Factory reset from userspace is not working as described in the documentation. /oem is actually RO and is missing the grubenv file. Actually even the grub entry is missing at all too.

**To Reproduce**
grub2-editenv /oem/grubenv set next_entry=statereset

**Expected behavior**
Device does a factory reset :)

**Logs**

**Additional context**

**Comment by mudler** [comment] 2023-01-11 21:01
Thanks @c0ffee for filing an issue! 

That's a good point - by default ARM images don't come with an OEM partition so docs aren't correct in such case. We should move to LVM, or either document how to set an OEM partition externally.

**Comment by c0ffee** [comment] 2023-01-12 10:23
The reset option is missing in the grub menu too

What would be then the way to do a reset on Wich a device?

In general I think LVM would be the best approach to have the same lock and feel

The limitation is probably the partition table at the moment right?

**Comment by mudler** [comment] 2023-01-12 11:05
> The reset option is missing in the grub menu too
> 
> What would be then the way to do a reset on Wich a device?

Once a partition labeled "COS_OEM" is found it is automatically loaded, however that needs further tweaking. Indeed the best approach is to move over something more flexible, like LVM.

> The limitation is probably the partition table at the moment right?

Correct

**Comment by jimmykarily** [comment] 2023-04-24 08:53
Waiting for this: https://github.com/kairos-io/kairos/issues/1271

**Comment by mauromorales** [comment] 2023-05-02 07:56
#1271 has been merged. I tested this and it is possible to create file `/oem/grubenv` and it persist over reboots, however the factory reset was not initiated on next reboot

**Comment by mudler** [comment] 2023-05-02 08:00
> #1271 has been merged. I tested this and it is possible to create file `/oem/grubenv` and it persist over reboots, however the factory reset was not initiated on next reboot

I think that has to do to the fact that there is no installation phase while flashing, so we miss the default grub configuration: https://github.com/kairos-io/kairos/blob/b42d35099b737a1cc35e471084b29345d3ff9a21/overlay/files/system/oem/21_grub.yaml#L13

**Comment by jimmykarily** [comment] 2023-05-12 09:03
Isn't this a problem too? https://github.com/kairos-io/kairos/blob/a5a8a5c65e7be69e53ab8b611bf73054e528f3de/overlay/files/system/oem/08_boot_assessment.yaml#L41

**Comment by jimmykarily** [comment] 2023-05-18 11:46
I copied the grub config in place and I now get this at boot:

![image](https://github.com/kairos-io/kairos/assets/2794419/b858ed9c-8b93-4ebb-b58b-ad43351bc6ed)

**Comment by jimmykarily** [comment] 2023-05-22 14:03
Regarding the missing grubenv file (see the description of the issue at the top), I think there is some detection happening here: https://github.com/kairos-io/packages/blob/1cfec31b9ca1097e1fbd96d9bac990c42d04e678/packages/static/grub-config/files/grub.cfg#L5

so the `grub2-editenv /oem/grubenv ` command actually creates that file, and the detection in the grub.cfg finds that and uses that. So as long as the grub config is in place, it should work. I need to try this out.

**Comment by jimmykarily** [comment] 2023-05-22 14:19
Indeed, with the fix in the draft PR in osbuilder (see linked PR above), when I run `grub2-editenv /oem/grubenv` and then `reboot`, the reset menu is selected when it boots.

Then is fails with this: 

![image](https://github.com/kairos-io/kairos/assets/2794419/e2ad6275-f811-4d91-95f8-a91a5521a5ec)

**Comment by jimmykarily** [comment] 2023-05-29 12:56
Actually it doesn't fail with the error above. After a while it continues. The problem seems to be that it can't even boot into recovery (not just "reset"). I flashed this image from quay.io: `kairos-opensuse-leap-arm-rpi-v2.2.0-rc1.img.xz` and this can't boot into recovery either. So, it doesn't have to do with any of my changes.

**Comment by mudler** [comment] 2023-05-31 09:00
looks like a regression in using LVM as partitioning. I can boot into recovery just fine on Nvidia AGX Orin

**Comment by jimmykarily** [comment] 2023-05-31 13:30
Maybe we need an `insmod lvm` line below this one: https://github.com/kairos-io/packages/blob/df06817de4b5bab8c1c0b572f9318880e4908659/packages/static/grub-config/files/grub.cfg#L56 ? I will try things

**Comment by jimmykarily** [comment] 2023-06-01 07:45
`insmod lvm` took the recovery boot a little bit further. It started printing things and then at some point it rebooted again. I will try with the serial cable to see if there was some error printed which I missed.

**Comment by jimmykarily** [comment] 2023-06-02 05:53
This should fix booting to recovery: https://github.com/kairos-io/kairos/pull/1471#event-9405444046

I'm not sure if `insmod lvm` is also needed. I will test with and without.

**Closed** 2023-06-02 10:42 UTC
Labels: bug, ARM
