### ISSUE TITLE
Uki: kairos-agent should check if an image is signed with compatible keys loaded on the system before upgrade

### ISSUE THREAD

**Issue by nianyush** [kairos-io/kairos#2421] opened 2024-04-03 06:38 UTC
Right now, kairos-agent wont check it and go for an upgrade. After reboot, the device will enter into following state and user cannot recover it or reset but can only do in new install. So kairos-agent should throw an error instead of upgrade with wrong image
![image](https://github.com/kairos-io/kairos/assets/5505684/a71f9c36-0c87-47bf-bdd2-3cbc850cea6b)

**Comment by Itxaka** [comment] 2024-04-03 06:42
I would even say that this is a bug rather than an enhancement as it's very easy to shoot yourself in the foot. Should be basic functionality.

Maybe we can use https://github.com/itxaka/go-secureboot which contains the talos secureboot libs extracted, when it's ready for generic consumption? It has functions related to signatures so maybe we can rework it to read signatures from files and confirm if they are enrolled in the current machine

**Comment by mudler** [comment] 2024-04-03 07:10
duplicate of #2200  ?

**Comment by mudler** [comment] 2024-04-03 07:12
closing as https://github.com/kairos-io/kairos/issues/2200 should cover this already

**Closed by mudler** 2024-04-03 07:12 UTC
Labels: enhancement, triage
