### ISSUE TITLE
AuroraBoot can't build a working ISO when ran as a pod in Kubernetes

### ISSUE THREAD

**Issue by sarg3nt** [kairos-io/kairos#3093] opened 2024-12-20 01:29 UTC
**Kairos version:**
 v3.2.4
 Rocky Linux 9

**CPU architecture, OS, and Version:**
Rocky linux 9
64bit

**Describe the bug**
We have a Jenkins pipeline, running in Jenkins that runs in a Kubernetes cluster.   
This Jenkins pipeline builds our AuroraBoot vSphere template for us that we then later clone and spin up to deploy Kairos based OSs.  
In general, what the pipeline does is this.  

1. Builds the Docker container that will be the OS that hosts AuroraBoot in the VM.  This OS is Kairos Rocky Kairos 3.2.4 core with Docker and a few other tools installed.
2. Uses the AuroraBoot container, deployed as a k8s pod  to build the ISO from the new container image that got built in step 1.
3. Uses Packer to fire up the ISO in vSphere to install Kairos and create the vSphere template.

This all worked until I upgraded the base Kairos OS to v3.2.4 and AuroraBoot to v0.4.3.  Now when the pipeline runs, the container is built, the ISO is built, but when the template is being created the OS fails to install completely.  (See screenshots below)

Here's the kicker.  If I run these exact same steps from my local machine, everything works fine.  
So maybe something on the AuroraBoot pod on the cluster?  The cluster node OS? Something else?
I downloaded the ISO that was generated on the k8s cluster and there's something "wrong" with it.

**Things Tried**

1. Moving back to the old version of the AuroraBoot container that is ran as a pod that builds the ISO.  Failed, still same messed up ISO.
2. Setting 
    ```yaml
          securityContext:
            capabilities:
              add: ["ALL"]
    ```
3. The Container that was built on the cluster was downloaded locally my workstation and I used AuroraBoot there to build the ISO and Packer to create the template. This worked fine.
4. The ISO that was built on the cluster using the AuroraBoot POD was downloaded locally and I then tried to use Packer to create the vSphere template and this failed with the same errors.  So it seems like it's the ISO that is created in the cluster.

**Logs**
![image](https://github.com/user-attachments/assets/35be2a39-db18-4643-9de7-b028d07a77a0)

![image](https://github.com/user-attachments/assets/8ffaf893-8865-47a7-b076-24c4668fd155)

![image](https://github.com/user-attachments/assets/392135a1-ddc5-4fbb-95bf-37e2c14635bb)

I can get the `rdsosreport.txt` file if needed but ran out of time today.  Let me know if you'd like it.
I can also try to use the same docker image to build an ISO locally and one on the cluster so we can see if there are obvious checksum differences and whatnot.

**Additional context**
The cluster is one of our older ones we will be replacing with our new V3 k8s architecture that is Kairos based.
Kubernetes 1.20.11
Ubuntu, kernel  5.4.0-202-generic

**Comment by Itxaka** [comment] 2024-12-20 09:53
umm that looks like an initramfs failure to mount the sysroot. During livecd run, immucore just waits for the sysroot to be available as its dracut the one doing all that stuff itself. 

So this points to a broken initramfs.

Would need the rdsosreport.txt file and also the build logs for the iso and base image, especially the initramfs build part as there may be something that changed and we have a broken initramfs (happened recently with debian testing IIRC)

**Comment by sarg3nt** [comment] 2024-12-20 22:25
Hey @Itxaka   The team and I have been playing with this off and on most of the day.  Getting logs out of the VM is proving to be stupid hard.  
The volume doesn't appear to be formatted?
In the emergency shell there are no disks under `/dev`
`lsblk` shows nothing .

Because of this, we don't have a way to copy the `rdsosreport.txt` off the VM.  Attaching another disk doesn't work and the vSphere console is the worst peace of software ever thrust upon humanity.  Which is to say, there is no Copy/Paste or file transfer.  

So I came up with a dumb way to get it to you.
Animated GIF time!
Sorry, this sucks. To make reading it easier you can download and open with [screen2gif](https://www.screentogif.com/), then scroll through it with your mouse wheel.  I had to lower the resolution to get it under the 10 MB Github file size limitation.  
![rdsosreport txt4](https://github.com/user-attachments/assets/37419f58-8c98-44d6-84e2-1354c0d556f6)

[auroraboot_iso_build.log](https://github.com/user-attachments/files/18215925/auroraboot_iso_build.log)
[auroraboot_container_build.log](https://github.com/user-attachments/files/18215926/auroraboot_container_build.log)

**Comment by Itxaka** [comment] 2024-12-23 11:45
mmmh I also noticed that it seems like the problem is that it cannot find the /dev/disk/by-label/COS_LIVE which is very weird! because I dont see any issues when building the container or the iso image, so teh iso should have that label for sure (you can confirm this by mounting the iso anywhere, windows or linux, it should show a COS_LIVE partition mounted in both Oses)

So again this points to something wrong during initramfs. no disks under dev as well smells really bad. Sounds like maybe udev didnt start or something? 

I can see this in the logs, which seems to skip the systemd-modules-load service which loads modules into the kernel
![Image](https://github.com/user-attachments/assets/c79fc4eb-a43e-46df-8422-1aebb365e29d)
![Image](https://github.com/user-attachments/assets/e8a2ef68-9fb9-4f4b-b3cd-ba543a53c7dd)

And then afterwards, looks like dm-mod canot be inserted into the kernel, which seems to be necessary to the livecd mounting dracut module:
![Image](https://github.com/user-attachments/assets/79549067-b62e-4134-b03c-16472d85f88b)


Could it be that you need some extra packages in your image? Its weird that dm-mod is not available, so maybe some linux-kernel-modules pacakge is not installed int he base image somehow? Its weird that this happens with a newer auroraboot. Maybe its the kairos base image instead, the one that its missing some packages?

I checked both rockylinux upstream image and kairos one and I can see the dm-mod module:



```
[root@fba117c82ac6 /]# cat /etc/kairos-release 
KAIROS_IMAGE_LABEL="9-core-amd64-generic-v3.2.4"
KAIROS_NAME="kairos-core-rockylinux-9"
KAIROS_ARTIFACT="kairos-rockylinux-9-core-amd64-generic-v3.2.4"
KAIROS_FLAVOR_RELEASE="9"
KAIROS_RELEASE="v3.2.4"
KAIROS_HOME_URL="https://github.com/kairos-io/kairos"
KAIROS_IMAGE_REPO="quay.io/kairos/rockylinux:9-core-amd64-generic-v3.2.4"
KAIROS_FLAVOR="rockylinux"
KAIROS_MODEL="generic"
KAIROS_ID="kairos"
KAIROS_VERSION="v3.2.4"
KAIROS_ID_LIKE="kairos-core-rockylinux-9"
KAIROS_VERSION_ID="v3.2.4"
KAIROS_PRETTY_NAME="kairos-core-rockylinux-9 v3.2.4"
KAIROS_GITHUB_REPO="kairos-io/kairos"
KAIROS_SOFTWARE_VERSION_PREFIX="k3s"
KAIROS_FAMILY="rhel"
KAIROS_VARIANT="core"
KAIROS_TARGETARCH="amd64"
KAIROS_REGISTRY_AND_ORG="quay.io/kairos"
KAIROS_BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
[root@fba117c82ac6 /]# find . -name dm-mod*
./usr/lib/modules/5.14.0-503.16.1.el9_5.x86_64/kernel/drivers/md/dm-mod.ko.xz
```

So it seems ok, but I noticed there is a discrepancy in the base image kernel version `5.14.0-503.16.1.el9_5.x86_64` and the one in the logs you gave us `5.14.0-427.37.1.el9_4.x86_64`.

Are you folks installing a specific kernel version from somewhere?

Im wondering if this is again an issue with Aurora and its cache directories, we had some reports of Aurora in containers using cached kernel versions, which could be this same issue. i.e. you build Kairos 3.2.2 which has kernel X and thats ok, and then build kairos 3.2.4 and that uses kernel X as it was cached, when it should have used kernel Y from the new rootfs.

Not sure how to confirm this, other than trying to clean up the cache directories or /tmp directories in the nodes building the isos and redo the build process with the latest kairos version to see if the kernel selected is correct.

But this makes sense, as it would result into this. Kairos is booting with kernel X and looking into /usr/lib/modules/X to get the modules to load, but the modules are in /usr/lib/modules/Y and the kernel is the incorrect version....

Seems that this is the more likely explanation for this weird issue.

**Comment by Itxaka** [comment] 2024-12-23 11:49
Tell me you used to build kairos 3.2.3 before moving to 3.2.4 because that would match the kernels :D

```
$ docker run -it --rm quay.io/kairos/rockylinux:9-core-amd64-generic-v3.2.3 ls /boot/ | grep vmlinuz-
vmlinuz-5.14.0-427.42.1.el9_4.x86_64

# itxaka @ zeus in ~/Downloads [12:47:15] 
$ docker run -it --rm quay.io/kairos/rockylinux:9-core-amd64-generic-v3.2.4 ls /boot/ | grep vmlinuz-
vmlinuz-5.14.0-503.16.1.el9_5.x86_64
```

```
👁 👃 👁 
   👄
```

**Closed** 2024-12-23 13:59 UTC
Labels: bug, triage, unconfirmed

**Comment by sarg3nt** [comment] 2024-12-26 17:23
Hi @Itxaka 
Thanks for taking a look at this.
I think you are getting this case and a previous one mixed up where I was using the wrong version because I had forgotten to build and push the new version of kairos.  That case was closed.  This case is different.

However, saying that, you are right on the money.  The ISO that was being built did have the wrong Kernel. Thanks for spotting that, it helped us track down the problem.  
Even though the OS container was correct, somehow the build systems was pulling the wrong one from our private container repo Artifactory.  We still aren't 100% why it was stuck but changing our naming scheme of the container seems to have fixed it, even though the old name was unique too.  
¯\_(ツ)_/¯

Anyway, so sorry to have taken time out of your schedule with this but your help was super valuable in helping us figure it out.

**Comment by Itxaka** [comment] 2024-12-26 17:38
No prob @sarg3nt this brought into light an underlying issue that has been happening with the newer auroraboot versions. Especially it seemed that  even if we didn't cache the build dir, it would still happening so this helped me track it down due to the very visible kernel version in bother versions 🥳
