### ISSUE TITLE
Reboot hangs for UKI images 

### ISSUE THREAD

**Issue by vipsharm** [kairos-io/kairos#2384] opened 2024-03-23 14:49 UTC
**Kairos version:**
3.0.1

**CPU architecture, OS, and Version:**
Ubuntu 23.10

After cluster is setup, rebooting the OS hangs in QEMU VM.

https://github.com/kairos-io/kairos/assets/13304280/d2ce43e7-5ab8-44f6-a922-05c745036aec

https://github.com/kairos-io/kairos/assets/13304280/7634db09-029a-47f9-80f5-920798ac7b98

**Comment by Itxaka** [comment] 2024-03-25 10:40
With longhorn installed and rebooting:

![image](https://github.com/kairos-io/kairos/assets/1447686/7e42fadf-fb78-47d7-8da2-439c906bd7d8)

**Comment by Itxaka** [comment] 2024-03-25 10:44
took a while but it restarted and then everything came up properly after a few minutes


![image](https://github.com/kairos-io/kairos/assets/1447686/a980f980-fa02-4923-9ea8-fd50be8402d0)

**Comment by mudler** [comment] 2024-03-27 08:24
@vipsharm as we can't reproduce this, can you share the ISO you are using so we can try to reproduce with that one? Also, did you give to the machine enough RAM/CPU resources?

**Comment by jimmykarily** [comment] 2024-03-29 16:45
it turns out the state partition gets filled up.  In my case it was even full after the upgrade before kubernetes even started"

![image](https://github.com/kairos-io/kairos/assets/2794419/7a976fdd-17db-4fa7-9333-6095f3691022)

 I increased the size of the state partition with:

```
#cloud-config
stylus:
  site:
    name: dimitris-edge-host-9
    edgeHostToken: <reducted>
    paletteEndpoint: api.dev.spectrocloud.com

install:
  device: "/dev/vda"
  auto: true
  partitions:
    state:
      size: 5000
      fs: ext4
stages:
  initramfs:
    - users:
        kairos:
          groups:
            - sudo
          passwd: kairos

```

and this allowed me to boot and see the Pods coming up. After everything was running, I did a cold `reboot` and waited until it reboots. Then the space issue came back:

![image](https://github.com/kairos-io/kairos/assets/2794419/4166bc50-fe6c-46fd-80bc-693345205511)

I think somehow containerd ends up writing the container filesystems on the state partition and it gets that filled up. Maybe there is some directory we should be mounting elsewhere and we don't?

**Comment by jimmykarily** [comment] 2024-04-01 09:17
The last thing that was printed before it started printing the "No space left on device" afaict was "simple directory" (about `/usr`) from here:

https://github.com/kairos-io/immucore/blob/8a142fe41f046098eb5676e055f50de02d342c13/pkg/state/steps_uki.go#L402

Given the errors refer to directories in /sysroot/usr` I guess the copying here is what fails: https://github.com/kairos-io/immucore/blob/8a142fe41f046098eb5676e055f50de02d342c13/pkg/state/steps_uki.go#L410

**Comment by jimmykarily** [comment] 2024-04-01 09:22
We only perform a check on the type of directory (mount point or not) on the top level dir (in this case `/usr`). What happens if a subdir is a mount point? `cp -a` will go crazy copying the mounted dir. Is it the case here as well? Is `/sysroot/usr/local/.state/` where the COS_STATE partition gets mounted?

**Comment by jimmykarily** [comment] 2024-04-01 09:26
What was the reason we only scanned top level directories again? (https://github.com/kairos-io/immucore/blob/8a142fe41f046098eb5676e055f50de02d342c13/pkg/state/steps_uki.go#L379). @Itxaka do you remember maybe?

**Comment by Itxaka** [comment] 2024-04-01 09:38
We didn't had anything in submounts that it's private no? So any submounts in the subdirs of the root dirs would be propagated when moving the mountpoints?


Something like that I think.

**Comment by jimmykarily** [comment] 2024-04-01 09:42
> We didn't had anything in submounts that it's private no? So any submounts in the subdirs of the root dirs would be propagated when moving the mountpoints?
> 
> Something like that I think.

maybe it's the order of things then? Maybe it starts copying `/usr` before it moves any mounts?

**Comment by Itxaka** [comment] 2024-04-01 09:45
Could it be that your issue come from ram? After all the new sysroot is mounted as tmpfs so it the VM has low memory or the image is big it can lead to ram exhaustion and that would cause the copy stuff to fail?

I just wonder why aren't we seeing the same issue anywhere else when testing?

**Comment by jimmykarily** [comment] 2024-04-01 11:35
I thought the same an increase my VMs RAM to 15Gb but the error is still there. We probably don't see the error because we are not running much on Kubernetes. If you see the screenshot with the errors, it's writing complete container filesystems there. This could easily get huge in size.

Given we are only trying to "fake" a chroot environment, I don't think it was every the intention to copy/duplicate such huge files. Also the directory they reside (`/sysroot/usr/local/.state`) should probably be a mount itself, not copied over.

**Comment by jimmykarily** [comment] 2024-04-01 11:50
I increased the VMs RAM to 30Gb and after taking quite some more time, it eventually booted with no disk errors. So this proves that the problem is the insane amount of data we are copying to the in-memory filesystem.

**Comment by Itxaka** [comment] 2024-04-01 12:31
blergh.

We tried to make it really simple but then it didnt work. So maybe we would need to rework it and mount things directly under the new fake sysroot to avoid all teh copying?

currently:
 - / is the sysroot
 - we do everything on it (agent stages, mounts, etcs)
 - we create the fake /sysroot and move everything in there
 - boot

We probably should do:
 - /sysroot as asysroot from start (We start on / need to mount everything to  /sysroot and chroot to it)
 - run then everything under the new fake sysroot as usual


The only reason we needed to move from / to /sysroot was that / was of type rootfs and that broke the kubernetes thingie
We created /sysroot as tempfs and remounted everything in there as a workaround and that made containerd and such behave.

So now we would need to rework it to be on the tmpfs from the scratch, just have a minimal / rootfs, move /proc /dev /run and such into /sysroot and chroot into it from the first immucore step so we run everything in the proper final system. 

We wil still need to do the Copy there BUT we do it before we do all the mounting of state and such, so its simpler as its basically a 1-1 copy, with no extra mounts in there

**Comment by Itxaka** [comment] 2024-04-01 12:35
I think its easier like that, doing all the preparation before the copying. Otherwise another approach is to make the cp/mount function recursive...... or use rsync or something more intelligent for the copying?

**Comment by jimmykarily** [comment] 2024-04-01 12:46
If it's possible to work on the tmpfs from the beginning I agree, it sounds like a better option. The rest sounds complicated and might result to different problems down the line.

**Comment by mudler** [comment] 2024-04-02 07:02
seem to be the case also for real HW (not only affecting VMs)

**Comment by mudler** [comment] 2024-04-03 07:38
https://github.com/kairos-io/immucore/pull/271

**Comment by antongisli** [comment] 2024-04-03 19:47
does this issue only occur on VMs?

**Comment by jimmykarily** [comment] 2024-04-04 06:20
> does this issue only occur on VMs?

No it shouldn't matter if it's a VM or not. It's not fixed on master.

**Comment by mudler** [comment] 2024-04-04 13:30
Closing now as this is fixed in master and will be part of the upcoming 3.0.4 release. (see https://github.com/kairos-io/kairos/issues/2428 )

**Closed by mudler** 2024-04-04 13:31 UTC
Labels: bug, prio: high
