### ISSUE TITLE
🐛 systemd-networkd cannot set hostname from DHCP, always set to localhost

### ISSUE THREAD

**Issue by ApolloDS** [kairos-io/kairos#280] opened 2022-10-24 21:01 UTC
**Kairos version:**
v1.1.3

**CPU architecture, OS, and Version:**
Running on VM with i686

**Describe the bug**
systemd-networkd cannot set hostname from DHCP, always set to localhost

**To Reproduce**
Check the logs:
journalctl -u systemd-networkd
...
Oct 24 19:40:06 localhost systemd[1]: Starting Network Configuration...
Oct 24 19:40:07 localhost systemd-networkd[1490]: ens19: Link UP
Oct 24 19:40:07 localhost systemd-networkd[1490]: ens19: Gained carrier
Oct 24 19:40:07 localhost systemd-networkd[1490]: ens18: Link UP
Oct 24 19:40:07 localhost systemd-networkd[1490]: ens18: Gained carrier
Oct 24 19:40:07 localhost systemd-networkd[1490]: lo: Link UP
Oct 24 19:40:07 localhost systemd-networkd[1490]: lo: Gained carrier
Oct 24 19:40:07 localhost systemd-networkd[1490]: ens19: Gained IPv6LL
Oct 24 19:40:07 localhost systemd-networkd[1490]: ens18: Gained IPv6LL
Oct 24 19:40:07 localhost systemd-networkd[1490]: Enumeration completed
Oct 24 19:40:07 localhost systemd[1]: Started Network Configuration.
Oct 24 19:40:08 localhost systemd-networkd[1490]: ens19: DHCPv4 address 10.11.12.13/24 via 10.11.12.1
Oct 24 19:40:08 localhost systemd-networkd[1490]: ens18: DHCPv4 address 192.168.1.13/24 via 192.168.1.1
Oct 24 19:40:08 localhost systemd-networkd[1490]: Could not set hostname: Access denied
Oct 24 19:40:08 localhost systemd-networkd[1490]: Could not set hostname: Access denied
Oct 24 19:40:08 localhost systemd-networkd[1490]: Could not set hostname: Access denied
Oct 24 19:40:22 localhost systemd-networkd[1490]: flannel.1: Link UP
Oct 24 19:40:22 localhost systemd-networkd[1490]: flannel.1: Gained carrier
Oct 24 19:40:23 localhost systemd-networkd[1490]: cni0: Link UP
Oct 24 19:40:23 localhost systemd-networkd[1490]: cni0: Gained carrier
Oct 24 19:40:23 localhost systemd-networkd[1490]: vethfd002f33: Link UP
Oct 24 19:40:23 localhost systemd-networkd[1490]: cni0: Lost carrier
Oct 24 19:40:23 localhost systemd-networkd[1490]: veth0e634ca9: Link UP
...
Error here:
Oct 24 19:40:08 localhost systemd-networkd[1490]: Could not set hostname: Access denied

**Expected behavior**
Should set the hostname according to DHCP

**Logs**
see above.

**Additional context**
Thank you @mudler for helping me in the matrix chat :-)

**Comment by mudler** [comment] 2022-10-24 21:46
right, seems polkit is missing from the images, thanks for filing up the issue!

**Comment by ApolloDS** [comment] 2022-10-25 11:10
Today I tested with kairos-ubuntu and there is the same problem. Maybe also polkit missing?
Need to do a test with kairos-alpine when I have time in some days...

**Comment by mudler** [comment] 2022-10-27 13:03
https://github.com/systemd/systemd/issues/13501

**Comment by Itxaka** [comment] 2023-01-27 13:37
adding policikitd && nscd to the ubuntu images makes the systemd-networkd -> systemd-hostnamed work, but it sets it as a transient name. as there is a static name set on the system already that has a higher priority so it doest get set. Very weird.

**Comment by Itxaka** [comment] 2023-01-31 13:26
On systems with polkit the issue is that polkit cant open the rules directories (700 permissions instead of 755) so it cant load the rules.

cant load the rules, cant allow systemd to set stuff :)

```
Jan 31 12:53:16 localhost polkitd[1429]: Loading rules from directory /etc/polkit-1/rules.d
Jan 31 12:53:16 localhost polkitd[1429]: Error opening rules directory: Error opening directory “/etc/polkit-1/rules.d”: Permission denied (g-file-error-quark, 2)
Jan 31 12:53:16 localhost polkitd[1429]: Loading rules from directory /usr/share/polkit-1/rules.d
Jan 31 12:53:16 localhost polkitd[1429]: Error opening rules directory: Error opening directory “/usr/share/polkit-1/rules.d”: Permission denied (g-file-error-quark, 2)
Jan 31 12:53:16 localhost polkitd[1429]: Finished loading, compiling and executing 0 rules
```


This is confirmed for tumbleweed. Changing the ownership of those dirs and restarting polkit+systemd-network makes the dhcp hostname appear:

```
localhost:~ # systemctl restart systemd-networkd
localhost:~ # hostnamectl
   Static hostname: (unset)                                           
Transient hostname: testname
         Icon name: computer-vm
           Chassis: vm 🖴
        Machine ID: 643f9ce11e6e4d5fb9d0e4ed63d90f38
           Boot ID: 521a5d6d01d54d618274487cc086da5d
    Virtualization: kvm
  Operating System: kairos-core-opensuse-tumbleweed v1.5.0-18-gc2c9421
            Kernel: Linux 6.1.8-1-default
      Architecture: x86-64
   Hardware Vendor: QEMU
    Hardware Model: Standard PC _Q35 + ICH9, 2009_
  Firmware Version: edk2-20221117gitfff6d81270b5-9.fc37
```


Will look into ubuntu afterwards, it may be the same issue :/

**Comment by Itxaka** [comment] 2023-02-02 13:12
Seems to be an either earthly issue or buildkit issue. Perms are lost when copying the docker/rootfs artifact 


during docker build target, there is several dirs not owned by root:

```
             +docker | --> RUN find / -type d ! -user root -print
             +docker | /etc/polkit-1/rules.d
             +docker | /usr/share/polkit-1/rules.d
             +docker | /run/systemd/netif
             +docker | /run/systemd/netif/leases
             +docker | /run/systemd/netif/links
             +docker | /run/systemd/netif/lldp
             +docker | /var/lib/nobody
             +docker | /var/lib/nfs/sm.bak
             +docker | /var/lib/nfs/sm
```

But once they are copied to the iso target those are fully lost:

```
                +iso | --> RUN find /build/image -type d ! -user root -print
                +iso | FLAVOR=opensuse-leap
```

**Comment by Itxaka** [comment] 2023-02-02 13:12
Earthfile seems to do the proper stuff, not altering the permissions so Im guessing its buildkit.

**Comment by Itxaka** [comment] 2023-02-02 13:30
It may have something to do with this from buildkit: https://github.com/moby/buildkit/issues/1941

**Comment by Itxaka** [comment] 2023-02-02 15:41
https://github.com/kairos-io/kairos/pull/805 Fixes this on opensuse.

On ubuntu, still not fixed. Networkd starts early, is not connected to dbus so does not set the hostname, then when it connects to dbus the static hostname is already set by something so nothing is done.

**Comment by Itxaka** [comment] 2023-02-02 18:24
Ubuntu: https://github.com/kairos-io/kairos/pull/806
Opensuse: https://github.com/kairos-io/kairos/pull/805

**Comment by Itxaka** [comment] 2023-02-02 19:15
And for debian/rocky/Fedora: https://github.com/kairos-io/kairos/pull/808

**Comment by Itxaka** [comment] 2023-02-03 09:57
Once https://github.com/kairos-io/kairos/pull/810/ gets merged we can close this, as it should be fixed in all systemd-networkd distros for the next release

**Closed** 2023-02-03 10:34 UTC
Labels: bug, qa
