### ISSUE TITLE
Booting fails on Raspberry Pi Computer Module 4

### ISSUE THREAD

**Issue by tantalic** [kairos-io/kairos#2099] opened 2023-12-19 18:56 UTC
**Kairos version:**
2.4.3

**CPU architecture, OS, and Version:**
arm64-rpi4

**Describe the bug**
After flashing Kairos onto a Raspberry Pi Compute Module 4 eMCC, the module fails to boot. The error message indicates that newer version is required:

```
Firmware: 469ea44619376439c801684745a12299645ae266 Mar 10 2021 10:12:47
start4.elf: is not compatible
This board requires newer software
```

I tested this with the latest openSUSE Leap and Ubuntu images and received the same error in both cases:

- `kairos-opensuse-leap-15.5-standard-arm64-rpi4-v2.4.3-k3sv1.28.2+k3s1.img`
- `kairos-ubuntu-23.04-standard-arm64-rpi4-v2.4.3-k3sv1.28.2+k3s1.img`

**To Reproduce**
1. Extract a RPI .img artifact from the published Docker images, [as documented here](https://kairos.io/docs/reference/image_matrix/#image-flavors)  
2. Flash the .img onto the Raspberry Pi Compute Module 4 eMCC
3. Boot the Raspberry Pi Compute Module 4

**Expected behavior**
Expected to boot as normal. Instead, booting fails with the error message indicated above.

**Additional context**
Photos of the boot process:
![IMG_5087](https://github.com/kairos-io/kairos/assets/88573/12e1cd65-9370-45f8-98d8-37d111251596)
![IMG_5090](https://github.com/kairos-io/kairos/assets/88573/19970df5-2f7c-48d6-bd46-adb938040776)

**Comment by tantalic** [comment] 2023-12-20 05:11
Same behavior is experienced with the latest Alpine image: `kairos-alpine-3.18-standard-arm64-rpi4-v2.4.3-k3sv1.27.6+k3s1.img`

**Comment by tantalic** [comment] 2023-12-23 07:44
I was able to do some more investigating today and I believe that I have confirmed that the issue is due to older versions of the Raspberry Pi firmware being included in the Kairos images.

I manually modified the `kairos-ubuntu-23.04-standard-arm64-rpi4-v2.4.3-k3sv1.28.2+k3s1.img ` image that was not working by copying the `.dtb`, `.dat`, `.elf`, and `overlays/*.dtbo` files from the [Raspberry Pi Firmware repo](https://github.com/raspberrypi/firmware/tree/master) (I used commit `c21815d`) to the `COS_GRUB` partition. This then booted successfully into Kairos/Ubuntu.

**Comment by jimmykarily** [comment] 2024-01-02 09:38
Hi @tantalic thanks for testing this. We don't have an Rpi CM4 around to test it.

We recently bumped the firmware versions here: https://github.com/kairos-io/packages/pull/515/files but we haven't released with it yet. We were using 3 years a old firmware package. Maybe this will fix this issue.

If you want to give it a try, you either have to wait until the next release of Kairos or build an image from `kairos-io/kairos` "master" branch.

**Comment by tantalic** [comment] 2024-01-02 16:46
@jimmykarily thanks for the update, given the age of the previous firmware used I suspect this will fix the issue. Unfortunately, the CM4s I was using are committed to something else at the moment, but I will see if I can free one up shortly after the next release.

**Comment by jimmykarily** [comment] 2024-01-15 06:40
v2.5.0 is out and probably fixes the problem. I'll close this for now. @tantalic feel free to re-open if the problem is still there. Thanks for reporting!

**Closed by jimmykarily** 2024-01-15 06:40 UTC
Labels: bug
