### ISSUE TITLE
:robot: Reset test is very flaky

### ISSUE THREAD

**Issue by Itxaka** [kairos-io/kairos#1708] opened 2023-08-10 08:59 UTC
**Kairos version:**
master

**CPU architecture, OS, and Version:**
all

**Describe the bug**
Reset test is failing a lot lately, we should check to see if we can improve it somehow to be less flaky or identify if there is a corner case where it makes it fail due to some specific issue.

**To Reproduce**
check reset jobs on build PRs pipeline

**Expected behavior**
doesnt fail all the time

**Logs**

**Additional context**

**Comment by jimmykarily** [comment] 2023-08-21 08:41
Let's wait until master CI is green ( to avoid debugging irrelevant issues ), then let's create a PR that only runs this test (disabling the rest) and finally let's keep triggering this until it fails, because this was not reproducible locally and we no longer have a link to a failed job.

We want the make sure there isn't something wrong with our reset workflow, that's why we are insisting on this one.

**Comment by mauromorales** [comment] 2023-08-29 07:21
The test has been consistently green in the past 10 runs ... will try to run multiple times locally to validate

**Comment by mauromorales** [comment] 2023-08-29 13:12
still green on every master run and for many local runs ... we've been merging changes on peg, upgrading packages so hard to tell if one of this changes fixed it, we also have the faster runners which might have made the test more reliable. Closing for now but feel free to re-open

**Closed by mauromorales** 2023-08-29 13:12 UTC
Labels: bug, ci
