### ISSUE TITLE
DHCP release when using ISO installs

### ISSUE THREAD

**Issue by spijker** [kairos-io/kairos#2103] opened 2023-12-21 18:59 UTC
**Kairos version:**
2.4.3

**CPU architecture, OS, and Version:**
amd64

**Describe the bug**

Environment: VMware ISO Installations Automated with Ansible

Issue Encountered:

During the automated deployment process, the ISO, when initiated, is exhibiting an unexpected behavior after installation and subsequent reboot.
The system is issuing a "DHCP release" command, which results in a delay as the installation process waits for the final IP address assignment.
This issue is causing an excessive consumption of IP addresses, with each node requiring 3 IP addresses per installation cycle.
Expected Behavior:

The installation process should complete smoothly without unnecessary IP address changes or delays waiting for IP reassignment.
Ideally, only one IP address should be utilized per node for each installation.
Steps to Reproduce:

Set up a virtual machine on VMware or KVM alike
Initiate an ISO installation.
Observe the behavior of the system post-installation, particularly after the reboot phase.
Impact:

This issue is causing delays in the automated deployment process and is leading to inefficient use of IP addresses in the network.
Additional Information:

No modifications or unusual settings have been applied that might typically lead to such behavior.
This issue has been consistently observed across multiple installation attempts.
Please investigate this issue as it affects the efficiency and resource management of our automated deployment process. 
Any insights or solutions to address this would be greatly appreciated.

**Comment by jimmykarily** [comment] 2024-01-03 15:36
I created a VM in qemu (virt-manager) in which I run this command:

```
tcpdump -i enp1s0 port 67 or port 68 -e -n -vv
```

This is monitoring DHCP messages in received in the specified interface.

In the same network, I started a VM using kairos image `kairos-opensuse-leap-15.5-standard-amd64-generic-v2.4.3-k3sv1.26.9+k3s1.iso`. 

I also created and mounted a datasource iso (following [this guide](https://kairos.io/docs/installation/automated/#data-source)) with this config:

```
#cloud-config

install:
  device: "/dev/vda"
  reboot: true
  poweroff: false
  auto: true # Required, for automated installations

users:
  - name: kairos
    passwd: kairos

k3s:
  enabled: true
```

After the kairos image has booted for the first time and until it has booted into the installed system, these are the DHCP messages received in the Ubuntu VM:

```
15:28:39.311497 52:54:00:a1:82:6d > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 322: (tos 0xc0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 308)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:a1:82:6d, length 280, xid 0xa7a1e9f1, secs 1, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:a1:82:6d
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Discover
	    Client-ID (61), length 19: hardware-type 255, 56:50:4d:98:00:02:00:00:ab:11:14:40:4e:29:39:9b:01:07
	    Parameter-Request (55), length 9: 
	      Subnet-Mask (1), Default-Gateway (3), Domain-Name-Server (6), Hostname (12)
	      Domain-Name (15), Static-Route (33), NTP (42), Unknown (120)
	      Classless-Static-Route (121)
	    MSZ (57), length 2: 1472
15:28:42.315286 52:54:00:a1:82:6d > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 334: (tos 0xc0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 320)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:a1:82:6d, length 292, xid 0xa7a1e9f1, secs 3, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:a1:82:6d
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Request
	    Client-ID (61), length 19: hardware-type 255, 56:50:4d:98:00:02:00:00:ab:11:14:40:4e:29:39:9b:01:07
	    Parameter-Request (55), length 9: 
	      Subnet-Mask (1), Default-Gateway (3), Domain-Name-Server (6), Hostname (12)
	      Domain-Name (15), Static-Route (33), NTP (42), Unknown (120)
	      Classless-Static-Route (121)
	    MSZ (57), length 2: 1472
	    Server-ID (54), length 4: 192.168.122.1
	    Requested-IP (50), length 4: 192.168.122.226



15:29:28.587377 52:54:00:a1:82:6d > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 322: (tos 0xc0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 308)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:a1:82:6d, length 280, xid 0x10f4d23e, secs 1, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:a1:82:6d
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Discover
	    Client-ID (61), length 19: hardware-type 255, 56:50:4d:98:00:02:00:00:ab:11:d5:cc:ce:3f:64:9f:cf:ad
	    Parameter-Request (55), length 9: 
	      Subnet-Mask (1), Default-Gateway (3), Domain-Name-Server (6), Hostname (12)
	      Domain-Name (15), Static-Route (33), NTP (42), Unknown (120)
	      Classless-Static-Route (121)
	    MSZ (57), length 2: 1472
15:29:31.593885 52:54:00:a1:82:6d > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 334: (tos 0xc0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 320)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:a1:82:6d, length 292, xid 0x10f4d23e, secs 3, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:a1:82:6d
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Request
	    Client-ID (61), length 19: hardware-type 255, 56:50:4d:98:00:02:00:00:ab:11:d5:cc:ce:3f:64:9f:cf:ad
	    Parameter-Request (55), length 9: 
	      Subnet-Mask (1), Default-Gateway (3), Domain-Name-Server (6), Hostname (12)
	      Domain-Name (15), Static-Route (33), NTP (42), Unknown (120)
	      Classless-Static-Route (121)
	    MSZ (57), length 2: 1472
	    Server-ID (54), length 4: 192.168.122.1
	    Requested-IP (50), length 4: 192.168.122.227
```

So the IP address did change once but I don't see a "release" message (I would expect something like: `DHCP-Message (53), length 1: Release`) .
We need to investigate what causes the address change after installation but that change only happens once (2 addresses vs 3 in the ticket description) and there is no "release" message sent afaict.

@spijker how are you testing the DHCP messages sent? Since you are doing an automated installation, how do you know that 3 different addresses were used?

**Comment by jimmykarily** [comment] 2024-01-04 06:03
I think the reason we get a different IP address after reboot is the different `Client-ID` field. I'm running an opensuse flavor and I think the settings in the `/etc/sysconfig/network/dhcp` file are relevant. Especially this one:

```
## Type:        string
## Default:     ""
#
# specify a client ID
#
# Specifies a client identifier string. By default an id derived from the
# hardware address of the network interface is sent as client identifier.
#
DHCLIENT_CLIENT_ID=""
```

I don't know what "derived" means here but it's definitely not just the MAC address because that doesn't seem to change in any of the messages (`52:54:00:a1:82:6d`)

**Comment by jimmykarily** [comment] 2024-01-04 06:30
It seems that `systemd-networkd` uses `/etc/machine-id` to generate the client id (https://manpages.ubuntu.com/manpages/jammy/man5/networkd.conf.5.html#[dhcpv4]%20section%20options).

I checked the value of `/etc/machine-id` while installing manually and it seems that our machine-id changes after installation:

```
before install (/etc/machine-id): 75d9a9406677269128d9f4ec65964d63
ip address: 192.168.122.33

after install (/etc/machine-id): 805fda9b7f26a953eeb4f18865964deb
ip address: 192.168.122.34
```

Relevant:
- https://github.com/kairos-io/kairos/issues/1627
- https://github.com/kairos-io/kairos/issues/1525#issuecomment-1600846263

It seems that we tried to fix this before, maybe it's a regression.

**Comment by jimmykarily** [comment] 2024-01-04 06:49
This is what takes care of `/etc/machine-id` (save and restore between reboots): https://github.com/kairos-io/packages/blob/640402e376486240dd58de778dec696b32071a9e/packages/static/kairos-overlay-files/files/system/oem/00_rootfs.yaml#L122-L143

but this doesn't try to persist the machine-id between the live system and the installed one. I don't think we ever tried to persist that. It's just one IP change only happening once (during installation). If it's a problem, we could try to find a way to avoid that.

**Comment by Itxaka** [comment] 2024-01-04 08:25
on systemd-network machines we should be able to change the default to use the MAC address for dhcp requests `ClientIdentifier=mac`

**Comment by jimmykarily** [comment] 2024-01-04 08:27
> on systemd-network machines we should be able to change the default to use the MAC address for dhcp requests `ClientIdentifier=mac`

that's also a possible fix. Would be nice if we can make it work with MAC in openrc too (for consistency).

**Comment by jimmykarily** [comment] 2024-01-04 08:36
If `dhdpcd` is used, then according to the man page:

```
$ man dhcpcd
...
       -I, --clientid clientid
               Send  the  clientid.   If the string is of the format 01:02:03 then it is encoded as hex.  For interfaces whose hardware address is longer than 8 bytes, or if the clientid is an empty string then dhcpcd
               sends a default clientid of the hardware family and the hardware address.
...
```

which means, maybe it already works like that on alpine so there is no fix needed. We need to check.

**Comment by jimmykarily** [comment] 2024-01-04 14:16
I tried with `kairos-alpine-3.18-standard-amd64-generic-v2.4.3-k3sv1.27.6+k3s1.iso`. Alpine sends the MAC as "Client ID" so the IP never changes:

```
14:12:35.986878 52:54:00:53:c4:5a > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 342: (tos 0x0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 328)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:53:c4:5a, length 300, xid 0x50b0eb2f, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:53:c4:5a
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Discover
	    MSZ (57), length 2: 576
	    Parameter-Request (55), length 7: 
	      Subnet-Mask (1), Default-Gateway (3), Domain-Name-Server (6), Hostname (12)
	      Domain-Name (15), BR (28), NTP (42)
	    Vendor-Class (60), length 12: "udhcp 1.36.1"
	    Client-ID (61), length 7: ether 52:54:00:53:c4:5a
14:12:39.029902 52:54:00:53:c4:5a > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 342: (tos 0x0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 328)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:53:c4:5a, length 300, xid 0x50b0eb2f, secs 3, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:53:c4:5a
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Request
	    Requested-IP (50), length 4: 192.168.122.87
	    Server-ID (54), length 4: 192.168.122.1
	    MSZ (57), length 2: 576
	    Parameter-Request (55), length 7: 
	      Subnet-Mask (1), Default-Gateway (3), Domain-Name-Server (6), Hostname (12)
	      Domain-Name (15), BR (28), NTP (42)
	    Vendor-Class (60), length 12: "udhcp 1.36.1"
	    Client-ID (61), length 7: ether 52:54:00:53:c4:5a
14:12:47.354001 52:54:00:53:c4:5a > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 590: (tos 0x0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 576)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:53:c4:5a, length 548, xid 0xf3c4a742, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:53:c4:5a
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Discover
	    MSZ (57), length 2: 576
	    Parameter-Request (55), length 8: 
	      Subnet-Mask (1), Default-Gateway (3), MTU (26), Unknown (252)
	      NTP (42), Domain-Name (15), Domain-Name-Server (6), Hostname (12)
	    Client-ID (61), length 7: ether 52:54:00:53:c4:5a
	    Hostname (12), length 9: "localhost"
14:12:47.366649 52:54:00:53:c4:5a > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 590: (tos 0x0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 576)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:53:c4:5a, length 548, xid 0xf3c4a742, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:53:c4:5a
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Request
	    Requested-IP (50), length 4: 192.168.122.87
	    Server-ID (54), length 4: 192.168.122.1
	    MSZ (57), length 2: 576
	    Parameter-Request (55), length 8: 
	      Subnet-Mask (1), Default-Gateway (3), MTU (26), Unknown (252)
	      NTP (42), Domain-Name (15), Domain-Name-Server (6), Hostname (12)
	    Client-ID (61), length 7: ether 52:54:00:53:c4:5a
	    Hostname (12), length 9: "localhost"






14:14:14.328559 52:54:00:53:c4:5a > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 342: (tos 0x0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 328)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:53:c4:5a, length 300, xid 0xb0ba931a, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:53:c4:5a
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Discover
	    MSZ (57), length 2: 576
	    Parameter-Request (55), length 7: 
	      Subnet-Mask (1), Default-Gateway (3), Domain-Name-Server (6), Hostname (12)
	      Domain-Name (15), BR (28), NTP (42)
	    Vendor-Class (60), length 12: "udhcp 1.36.1"
	    Client-ID (61), length 7: ether 52:54:00:53:c4:5a
14:14:17.352486 52:54:00:53:c4:5a > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 342: (tos 0x0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 328)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:53:c4:5a, length 300, xid 0xb0ba931a, secs 3, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:53:c4:5a
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Request
	    Requested-IP (50), length 4: 192.168.122.87
	    Server-ID (54), length 4: 192.168.122.1
	    MSZ (57), length 2: 576
	    Parameter-Request (55), length 7: 
	      Subnet-Mask (1), Default-Gateway (3), Domain-Name-Server (6), Hostname (12)
	      Domain-Name (15), BR (28), NTP (42)
	    Vendor-Class (60), length 12: "udhcp 1.36.1"
	    Client-ID (61), length 7: ether 52:54:00:53:c4:5a
14:14:30.963171 52:54:00:53:c4:5a > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 590: (tos 0x0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 576)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:53:c4:5a, length 548, xid 0x1a0de40f, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:53:c4:5a
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Discover
	    MSZ (57), length 2: 576
	    Parameter-Request (55), length 8: 
	      Subnet-Mask (1), Default-Gateway (3), MTU (26), Unknown (252)
	      NTP (42), Domain-Name (15), Domain-Name-Server (6), Hostname (12)
	    Client-ID (61), length 7: ether 52:54:00:53:c4:5a
	    Hostname (12), length 9: "localhost"
14:14:30.975710 52:54:00:53:c4:5a > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 590: (tos 0x0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 576)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:53:c4:5a, length 548, xid 0x1a0de40f, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:53:c4:5a
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Request
	    Requested-IP (50), length 4: 192.168.122.87
	    Server-ID (54), length 4: 192.168.122.1
	    MSZ (57), length 2: 576
	    Parameter-Request (55), length 8: 
	      Subnet-Mask (1), Default-Gateway (3), MTU (26), Unknown (252)
	      NTP (42), Domain-Name (15), Domain-Name-Server (6), Hostname (12)
	    Client-ID (61), length 7: ether 52:54:00:53:c4:5a
	    Hostname (12), length 9: "localhost"

```

If we just do the same on systemd, we should be done.

**Comment by jimmykarily** [comment] 2024-01-04 14:25
We already set `ClientIdentifier=mac` (https://github.com/kairos-io/packages/blob/1d5bb2414bfcd019f22768b47598ee6c3dd97b07/packages/static/kairos-overlay-files/files/system/oem/05_network.yaml#L22). It's just not part of any release yet.

(I guess world kept turning while I was on vacation :D : https://github.com/kairos-io/packages/pull/587/files)

**Comment by jimmykarily** [comment] 2024-01-04 14:40
I built and opensuse image from `master` and this is the result:

```
14:36:31.588523 52:54:00:c2:b4:08 > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 310: (tos 0xc0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 296)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:c2:b4:08, length 268, xid 0x7b242e13, secs 1, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:c2:b4:08
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Discover
	    Client-ID (61), length 7: ether 52:54:00:c2:b4:08
	    Parameter-Request (55), length 9: 
	      Subnet-Mask (1), Default-Gateway (3), Domain-Name-Server (6), Hostname (12)
	      Domain-Name (15), Static-Route (33), NTP (42), Unknown (120)
	      Classless-Static-Route (121)
	    MSZ (57), length 2: 1472
14:36:34.595737 52:54:00:c2:b4:08 > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 322: (tos 0xc0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 308)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:c2:b4:08, length 280, xid 0x7b242e13, secs 3, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:c2:b4:08
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Request
	    Client-ID (61), length 7: ether 52:54:00:c2:b4:08
	    Parameter-Request (55), length 9: 
	      Subnet-Mask (1), Default-Gateway (3), Domain-Name-Server (6), Hostname (12)
	      Domain-Name (15), Static-Route (33), NTP (42), Unknown (120)
	      Classless-Static-Route (121)
	    MSZ (57), length 2: 1472
	    Server-ID (54), length 4: 192.168.122.1
	    Requested-IP (50), length 4: 192.168.122.84




################ Installation is done here 


14:38:08.915455 52:54:00:c2:b4:08 > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 310: (tos 0xc0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 296)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:c2:b4:08, length 268, xid 0x99ec0707, secs 1, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:c2:b4:08
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Discover
	    Client-ID (61), length 7: ether 52:54:00:c2:b4:08
	    Parameter-Request (55), length 9: 
	      Subnet-Mask (1), Default-Gateway (3), Domain-Name-Server (6), Hostname (12)
	      Domain-Name (15), Static-Route (33), NTP (42), Unknown (120)
	      Classless-Static-Route (121)
	    MSZ (57), length 2: 1472
14:38:08.915694 52:54:00:c2:b4:08 > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 322: (tos 0xc0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 308)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 52:54:00:c2:b4:08, length 280, xid 0x99ec0707, secs 1, Flags [none] (0x0000)
	  Client-Ethernet-Address 52:54:00:c2:b4:08
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message (53), length 1: Request
	    Client-ID (61), length 7: ether 52:54:00:c2:b4:08
	    Parameter-Request (55), length 9: 
	      Subnet-Mask (1), Default-Gateway (3), Domain-Name-Server (6), Hostname (12)
	      Domain-Name (15), Static-Route (33), NTP (42), Unknown (120)
	      Classless-Static-Route (121)
	    MSZ (57), length 2: 1472
	    Server-ID (54), length 4: 192.168.122.1
	    Requested-IP (50), length 4: 192.168.122.84
```

The client sends the mac address as "Client ID" and the IP doesn't change.

It means, it should be fixed in the next release. I'll keep this under review until we release and then close.

@spijker let me know if I missed something.

**Comment by jimmykarily** [comment] 2024-01-15 06:31
kairos v2.5.0 is out and includes the fix. I'm closing this.

**Closed by jimmykarily** 2024-01-15 06:31 UTC
Labels: bug
