### ISSUE TITLE
kairos-agent [upgrade|install] --source should work

### ISSUE THREAD

**Issue by jimmykarily** [kairos-io/kairos#1837] opened 2023-09-20 10:34 UTC
Originally discussed here: https://github.com/kairos-io/kairos/issues/1800
and here: https://spectrocloudcommunity.slack.com/archives/C04B1833NEA/p1695046729703839

`--source` flag is being ignored. Same thing happens on upgrade or install (manual-install too?)

**Comment by Itxaka** [comment] 2023-09-20 11:01
install doesnt support --source
reset doesnt support --source

Only upgrade supports --source flag

**Comment by Itxaka** [comment] 2023-09-20 11:04
upgrade --source works as expected.

```
kairos@localhost:~> sudo kairos-agent --debug upgrade --recovery --source oci:test/whatever
WARNING: jsonschema: '' does not validate with file:///home/kairos/schema.json#/required: missing properties: 'users'
INFO[2023-09-20T11:02:51Z] kairos-agent version v2.2.12                 
DEBU[2023-09-20T11:02:51Z] Loaded config: &config.Config{
  Install: &config.Install{
    Auto: false,
    Reboot: false,
    NoFormat: false,
    Device: "/dev/vda",
    Poweroff: false,
    GrubOptions: map[string]string(nil), // p0
    Bundles: nil,
    Encrypt: nil,
    SkipEncryptCopyPlugins: false,
    Env: nil,
    Image: "",
    EphemeralMounts: nil,
    BindMounts: nil,
  },
  Config: collector.Config{
    "install": collector.Config{
      "device": "/dev/vda",
    },
    "name": "Config generated by the installer",
    "stages": collector.Config{
      "initramfs": []interface {}{
        collector.Config{
          "users": collector.Config{
            "kairos": collector.Config{
              "groups": []interface {}{
                "admin",
              },
              "name": "kairos",
              "passwd": "kairos",
            },
          },
        },
      },
    },
  },
  ConfigURL: "",
  Options: p0,
  FailOnBundleErrors: false,
  Bundles: nil,
  GrubOptions: p0,
  Env: nil,
  Debug: false,
  Strict: false,
  CloudInitPaths: nil,
  EjectCD: false,
  Logger: &logrus.Logger{ // p1
    Out: &os.File{},
    Hooks: logrus.LevelHooks{},
    Formatter: &logrus.TextFormatter{
      ForceColors: true,
      DisableColors: false,
      ForceQuote: false,
      DisableQuote: false,
      EnvironmentOverrideColors: false,
      DisableTimestamp: false,
      FullTimestamp: true,
      TimestampFormat: "",
      DisableSorting: false,
      SortingFunc: ,
      DisableLevelTruncation: false,
      PadLevelText: false,
      QuoteEmptyFields: false,
      FieldMap: logrus.FieldMap(nil),
      CallerPrettyfier: ,
    },
    ReportCaller: false,
    Level: 5,
    ExitFunc: os.Exit,
    BufferPool: nil,
  },
  Fs: &vfs.osfs{}, // p2
  Mounter: &mount.Mounter{},
  Runner: &v1.RealRunner{ // p3
    Logger: p1,
  },
  Syscall: &v1.RealSyscall{},
  CloudInitRunner: &cloudinit.YipCloudInitRunner{},
  ImageExtractor: v1.OCIImageExtractor{},
  Client: &http.Client{},
  Platform: &v1.Platform{
    OS: "linux",
    Arch: "x86_64",
    GolangArch: "amd64",
  },
  Cosign: false,
  Verify: false,
  CosignPubKey: "",
  Arch: "x86_64",
  SquashFsCompressionConfig: []string{},
  SquashFsNoCompression: true,
} 
WARN[2023-09-20T11:02:53Z] Failed to infer size for images: GET https://index.docker.io/v2/test/whatever/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:test/whatever Type:repository]] 
DEBU[2023-09-20T11:02:53Z] Loaded upgrade spec: &v1.UpgradeSpec{
  RecoveryUpgrade: true,
  Active: v1.Image{
    File: "/run/initramfs/cos-state/cOS/transition.img",
    Label: "COS_ACTIVE",
    Size: 3072,
    FS: "ext2",
    Source: &v1.ImageSource{},
    MountPoint: "/run/cos/transition",
    LoopDevice: "",
  },
  Recovery: v1.Image{
    File: "/run/cos/recovery/cOS/transition.img",
    Label: "COS_SYSTEM",
    Size: 3072,
    FS: "ext2",
    Source: &v1.ImageSource{},
    MountPoint: "/run/cos/transition",
    LoopDevice: "",
  },
  GrubDefEntry: "",
  Reboot: false,
  PowerOff: false,
  ExtraDirsRootfs: nil,
  Passive: v1.Image{
    File: "/run/initramfs/cos-state/cOS/passive.img",
    Label: "COS_PASSIVE",
    Size: 3072,
    FS: "ext2",
    Source: &v1.ImageSource{},
    MountPoint: "",
    LoopDevice: "",
  },
  Partitions: v1.ElementalPartitions{
    BIOS: nil,
    EFI: nil,
    OEM: &v1.Partition{
      Name: "vda2",
      FilesystemLabel: "COS_OEM",
      Size: 64,
      FS: "ext4",
      Flags: nil,
      MountPoint: "/oem",
      Path: "/dev/vda2",
      Disk: "/dev/vda",
    },
    Recovery: &v1.Partition{
      Name: "vda3",
      FilesystemLabel: "COS_RECOVERY",
      Size: 2822,
      FS: "ext4",
      Flags: nil,
      MountPoint: "/run/cos/recovery",
      Path: "/dev/vda3",
      Disk: "/dev/vda",
    },
    State: &v1.Partition{
      Name: "vda4",
      FilesystemLabel: "COS_STATE",
      Size: 4933,
      FS: "ext4",
      Flags: nil,
      MountPoint: "/run/initramfs/cos-state",
      Path: "/dev/vda4",
      Disk: "/dev/vda",
    },
    Persistent: &v1.Partition{
      Name: "vda5",
      FilesystemLabel: "COS_PERSISTENT",
      Size: 15730,
      FS: "ext4",
      Flags: nil,
      MountPoint: "/run/cos/persistent",
      Path: "/dev/vda5",
      Disk: "/dev/vda",
    },
  },
  State: &v1.InstallState{
    Date: "2023-09-20T10:59:24Z",
    Partitions: map[string]*v1.PartitionState{
      "oem": &v1.PartitionState{
        FSLabel: "COS_OEM",
        Images: map[string]*v1.ImageState(nil), // p0
      },
      "persistent": &v1.PartitionState{
        FSLabel: "COS_PERSISTENT",
        Images: p0,
      },
      "recovery": &v1.PartitionState{
        FSLabel: "COS_RECOVERY",
        Images: map[string]*v1.ImageState{
          "recovery": &v1.ImageState{
            Source: &v1.ImageSource{},
            SourceMetadata: nil,
            Label: "COS_SYSTEM",
            FS: "ext2",
          },
        },
      },
      "state": &v1.PartitionState{
        FSLabel: "COS_STATE",
        Images: map[string]*v1.ImageState{
          "active": &v1.ImageState{
            Source: &v1.ImageSource{},
            SourceMetadata: nil,
            Label: "COS_ACTIVE",
            FS: "ext2",
          },
          "passive": &v1.ImageState{
            Source: &v1.ImageSource{},
            SourceMetadata: nil,
            Label: "COS_PASSIVE",
            FS: "ext2",
          },
        },
      },
    },
  },
} 
DEBU[2023-09-20T11:02:53Z] Mounting partition COS_STATE                 
DEBU[2023-09-20T11:02:53Z] Mounting partition COS_RECOVERY              
DEBU[2023-09-20T11:02:53Z] mounting persistent partition                
DEBU[2023-09-20T11:02:53Z] Mounting partition COS_PERSISTENT            
INFO[2023-09-20T11:02:53Z] Applying 'before-upgrade' hook               
INFO[2023-09-20T11:02:53Z] Running before-upgrade hook                  
DEBU[2023-09-20T11:02:53Z] Cloud-init paths set to [/system/oem /oem/ /usr/local/cloud-config/] 
INFO[2023-09-20T11:02:53Z] Running stage: before-upgrade.before         
INFO[2023-09-20T11:02:53Z] Done executing stage 'before-upgrade.before' 
INFO[2023-09-20T11:02:53Z] Running stage: before-upgrade                
INFO[2023-09-20T11:02:53Z] Done executing stage 'before-upgrade'        
INFO[2023-09-20T11:02:53Z] Running stage: before-upgrade.after          
INFO[2023-09-20T11:02:53Z] Done executing stage 'before-upgrade.after'  
INFO[2023-09-20T11:02:53Z] Running stage: before-upgrade.before         
INFO[2023-09-20T11:02:53Z] Done executing stage 'before-upgrade.before' 
INFO[2023-09-20T11:02:53Z] Running stage: before-upgrade                
INFO[2023-09-20T11:02:53Z] Done executing stage 'before-upgrade'        
INFO[2023-09-20T11:02:53Z] Running stage: before-upgrade.after          
INFO[2023-09-20T11:02:53Z] Done executing stage 'before-upgrade.after'  
INFO[2023-09-20T11:02:53Z] deploying image test/whatever:latest to /run/cos/recovery/cOS/transition.img 
INFO[2023-09-20T11:02:53Z] Creating file system image /run/cos/recovery/cOS/transition.img with size 3072Mb 
DEBU[2023-09-20T11:02:53Z] Running cmd: 'mkfs.ext2 -L COS_SYSTEM /run/cos/recovery/cOS/transition.img' 
DEBU[2023-09-20T11:02:53Z] Mounting image COS_SYSTEM                    
DEBU[2023-09-20T11:02:53Z] Running cmd: 'losetup --show -f /run/cos/recovery/cOS/transition.img' 
INFO[2023-09-20T11:02:53Z] Copying test/whatever:latest source to /run/cos/transition 
DEBU[2023-09-20T11:02:54Z] Unmounting image COS_SYSTEM                  
DEBU[2023-09-20T11:02:54Z] Running cmd: 'losetup -d /dev/loop1'         
ERRO[2023-09-20T11:02:54Z] Failed deploying image to file '/run/cos/recovery/cOS/transition.img': GET https://index.docker.io/v2/test/whatever/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:test/whatever Type:repository]] 
DEBU[2023-09-20T11:02:54Z] [Cleanup] Removing /run/cos/recovery/cOS/transition.img 
DEBU[2023-09-20T11:02:54Z] Unmounting partition COS_RECOVERY            
DEBU[2023-09-20T11:02:54Z] Mounting partition COS_STATE                 
1 error occurred:
	* GET https://index.docker.io/v2/test/whatever/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:test/whatever Type:repository]]


kairos@localhost:~> 

````

@jimmykarily please close this as its not a real issue, the problem lies in the other issue opened and looks like its a very specific way of triggering it which has nothing to do with the --source flag working on normal upgrades. I could not even reproduce what is on the other issue locally.

**Comment by jimmykarily** [comment] 2023-09-20 14:11
I was confused by the slack conversation and thought it was the same issue. This one could be seen as an enhancement to support `--source` on "install". I'll leave it open to discuss in planning.

**Closed** 2023-10-02 09:55 UTC
Labels: enhancement
